### ISSUE TITLE
Build and dev are not working

### ISSUE THREAD

**Issue by nrep** [puikinsh/Adminator-admin-dashboard#10]
I am running the dev and build scripts using yarn. The problem is, they are showing that everything is done but, in case of the dev script that is telling me to go to http://0.0.0.0:3000, when i go to that adress in my browser it seems like nothing is running there. I also tried to build the project but I am having a project which seems like it has not been styled. I spent a lot of time on this, help will be appreciated.

**Comment by AndreiCN** [comment]
Did you tried with NPM too ? I'm asking in order to see if that happens using Yarn only.

**Comment by AmrSubZero** [comment]
It's also doing the same with **NPM**!
```http://0.0.0.0:3000/```

**Comment by rr-mdalauddin-alamin** [comment]
i have a problem while run and build.

webpack-dashboard -t 'Project' -- webpack-dev-server

[npm-debug.log](https://github.com/puikinsh/Adminator-admin-dashboard/files/1651252/npm-debug.log)

**Comment by pideee** [comment]
Are you working on Windows? Try http://localhost:3000

**Comment by rr-mdalauddin-alamin** [comment]
@pideee  no i am using ubuntu 16.04 LTS version. 
i have node.js and npm installed updated version.

**Comment by AndreiCN** [comment]
After "npm run dev" , load it on the server created by webpack "http://localhost:3000/index.html" and will work for sure, not just "http://0.0.0.0:3000/" or "http://127.0.0.1:3000" they are the same thing.
