### ISSUE TITLE
Explanation of classes and CSS

### ISSUE THREAD

**Issue by bilogic** [puikinsh/Adminator-admin-dashboard#102]
<h1>Support request</h1>
<h1>Documentation issue</h1>

I'm trying to make some modifications to chat.html, but have trouble understanding the classes and CSS.
e.g. classes like ```p-15``` ```bdrs-0``` ```bdw-0``` don't make any sense to me.

# Current behavior
There isn't a "more" icon at the userlist of chat.html

# Expected behavior 
1. Add a row on top of "Search Contacts" with a left-aligned icon photo + right-aligned "more" icon
OR 
2. Add a right-aligned "more" icon to the "Search Contacts"

Thank you!

**Comment by krzysiekpiasecki** [comment]
>  classes like p-15 bdrs-0 bdw-0 don't make any sense to me.

`bdrs-0` means border radius 0, `bdw-0` means border width 0. Why do you think that they don't make any sense?

> Add a row on top of "Search Contacts" 

If you found that there should be an additional icon, please make a pull request.

**Comment by bilogic** [comment]
Hi, thank you for the clarification. They only make sense after your explanation, but it would not be possible for me to guess with confidence what they do. Is there a glossary or something? Thank you.

**Comment by krzysiekpiasecki** [comment]
You should be familiar with web inspector which is attached to every browser. With inspector you can "debug" CSS rules.

**Comment by DuudeXX8** [comment]
Should you tell me pls where I can find the include path of fonts.There are including via fonts.scss but after compilation I can't find a include path in style.css or in index.html please help.

**Comment by bilogic** [comment]
@krzysiekpiasecki think I got it now. Thank you.
