### ISSUE TITLE
How to use the datatable and some other sub-components

### ISSUE THREAD

**Issue by damms005** [puikinsh/Adminator-admin-dashboard#106]
Please how does the datatable work? 
There are no details about this in any place, including simple details like how to populate it, etc.

Also, all assets seems to be lumped together into a single file after build, so it is unclear on how to tweak some simple things like the map displayed on the main dashboard, etc.

Kindly provide these details.

Thanks

**Comment by krzysiekpiasecki** [comment]
> Please how does the datatable work?

Datatable is an external library. Documentation is founded here: https://datatables.net/manual/. All external libraries are listed here https://github.com/puikinsh/Adminator-admin-dashboard/blob/master/package.json. If you have a question how to use these external libraries, you can post on their support forums. 

> Also, all assets seems to be lumped together into a single file after build, so it is unclear on how to tweak some simple things like the map displayed on the main dashboard, etc.

You must be familiar with Webpack - https://webpack.js.org

Please close this ticket, if you have no more questions.

**Comment by damms005** [comment]
Thanks

**Comment by damms005** [comment]
@krzysiekpiasecki btw, kindly point me to how I can easily add a simple, external, independent, non-webpack js library like (watable)[https://github.com/wootapa/watable] to this project? (currently when I add watable, its dropdown does not work - I guess something about the webpack vendor.js is blocking it)

**Comment by damms005** [comment]
@krzysiekpiasecki btw, kindly point me to how I can easily add a simple, external, independent, non-webpack js library like (watable)[https://github.com/wootapa/watable] to this project? (currently when I add watable, its dropdown does not work - I guess something about the webpack vendor.js is blocking it)

**Comment by krzysiekpiasecki** [comment]
Add dependency to `package.json` then rebuild the app with `npm run build`.

**Comment by damms005** [comment]
But watable is not a node module. It is not resolved/downloaded by npm during build. Kindly help.

**Comment by krzysiekpiasecki** [comment]
Use bower manager instead. Install library, import, and the rebuild the app.

**Comment by damms005** [comment]
Ok. Thanks a lot
