### ISSUE TITLE
Cannot POST

### ISSUE THREAD

**Issue by twimnox** [puikinsh/Adminator-admin-dashboard#107]
Hello. I'm trying to POST from a forms page to itself, but i get the following error:
"Cannot POST /forms.html"

What could it be?

here's the form html with POST method. This piece of code can be found in "forms.html" from the template:

https://jsfiddle.net/qhrcy0e7/1/

thanks in advance!

**Comment by krzysiekpiasecki** [comment]
@twimnox Can't reproduce http://adminator-bootstrap4-65.surge.sh/forms.html. Can you attach the screenshot of this error?

**Comment by shirshak55** [comment]
@twimnox check if there is javascript error . This is just a html and css theme. It must be javascript. and I think to post you will need server side. What are you doing in post request to forms.html?

**Comment by twimnox** [comment]
Here is the console log:

forms.html:1 POST http://localhost:3000/forms.html 404 (Not Found)

Just added the method for one of the forms: <form method="POST">
It works with "GET" though.

**Comment by shirshak55** [comment]
@twimnox  Why should you be able to post on forms.html? What is meaning of POST request on forms.html. It is just a html file. And in HTML file I think we can only use GET isn't it?

**Comment by twimnox** [comment]
Pardon my newbieness on front end development 😞  What I want to do is using the values from my form fields to update a Chart that is placed in the very same page with Javascript. POST method just seemed like a cleaner way of doing this.

**Comment by shirshak55** [comment]
Ok lets keep this issue cleaner. Lets discuss it in facebook so I can help you. Send me message at https://www.facebook.com/shirshak55

OR do you have twitter etc?

**Comment by mkran** [comment]
I am having a similar issue. I would like to upload a file to the server. For that I use the form to select a file to upload. Please tell me what I am doing wrong.

Here is my index.html:
```
<!DOCTYPE html>
<html>
...
...
<form method="post" enctype="multipart/form-data">
  <div>
    <label for="file">Choose file to upload</label>
    <input type="file" id="file" name="file" multiple>
  </div>
  <div>
    <button>Submit</button>
  </div>
</form>
...
...
</html>
```
Here is the output at `http://localhost:3001/index.html`:
```
Cannot POST /index.html
```

**Comment by shirshak55** [comment]
Which server side have you implemented

**Comment by jepperaskdk** [comment]
I believe a form without an action will just cause a reload, if not intercepted by javascript. You should add an action to the form, like `<form method="post" action="somefile.php">` - and this file should be capable of handling the POST serverside.

**Comment by punitj1221** [comment]
> Pardon my newbieness on front end development 😞 What I want to do is using the values from my form fields to update a Chart that is placed in the very same page with Javascript. POST method just seemed like a cleaner way of doing this.

when you want to run PHP on same page as of the content then your page should be having extension of '.php' instead of '.html'. Change the page name to .php and add the php content for post there itself. 
IN ALL,
YOU CANNOT RUN PHP ON THE SAME PAGE WITH HTML EXTENSION. YOU NEED TO CHANGE THE EXTENSION TO .php AND ADD THE PHP THERE.
I have done one thing for you. You can do more  the same way.
I have done it for Basic Forms. Please check and let me know if its the same thing you wanted to do!?`<main class='main-content bgc-grey-100'>
          <div id='mainContent'>
            ....
                    <form action="" method="POST">
                    ....
 <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                        ....
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                      ...
                      <input type="submit" class="btn btn-primary" value="Submit">
                  </form>
                  ---
              
              <?php 
              if($_SERVER['REQUEST_METHOD']=="POST")
              {
                  if(isset($_POST['email']))
                  {
                    $name=$_POST['email'];
                  }
                  if(isset($_POST['password']))
                  {
                     $password=$_POST['password'];
                  }
                  echo $name;
                  echo $password;
              }
              ?>`
Also please change the extension of the file to '.php'  from '.html'. I have also chaged the button with button tag to <input type="submit"> as its the correct way of doing it.
Please let me know about it.
