### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by Muhsinrbn** [puikinsh/Adminator-admin-dashboard#109]
<h1>Bug report</h1>
<h1>Feature request</h1>
<h1>Support request</h1>
<h1>Documentation issue</h1>

# Current behavior

# Expected behavior 

# Environment
Platform: 
Browser: 

For building issues:
Node:           
NPM:          

<img width="1440" alt="screen shot 2018-08-10 at 12 36 42 pm" src="https://user-images.githubusercontent.com/37010421/43943698-16340288-9c9a-11e8-814c-0c6efa2b2b58.png">

**Comment by krzysiekpiasecki** [comment]
@Muhsinrbn  Still got this issue? Which versions of Node and NPM ?

**Comment by gnovaro** [comment]
![captura de pantalla de 2018-12-13 21-18-51](https://user-images.githubusercontent.com/270990/49975591-5e897000-ff1d-11e8-99e4-a95b3c8b50c0.png)
I run the stepts, but i can't install in localhost in recent clone

node -v
v8.10.0

npm -v
3.5.2

**Comment by krzysiekpiasecki** [comment]
@Muhsinrbn Upgrade npm to 5.6.0 for node 8.10.0. Closed due to inactivity and resolve hint.
