### ISSUE TITLE
Syntax error, unrecognized expression

### ISSUE THREAD

**Issue by davorpeic** [puikinsh/Adminator-admin-dashboard#11]
Hi, once implemented, I see this console error
```
Uncaught Error: Syntax error, unrecognized expression: [href*="www.mydomain.com"
    at Function.e.error (vendor.js:1)
```

any idea why I'm getting it?

**Comment by avinassh** [comment]
Same, I am also getting this error.

**Comment by ghost** [comment]
Hi, this problem is caused by a missing "]" in line 31 at "src/assets/scripts/utils/index.js".
-`.not(`[href*="${window.location.host}"`)`
+`.not(`[href*="${window.location.host}"]`)`
Best regards.

**Comment by AndreiCN** [comment]
Thank you @thiago0b12  for you contribution !
