### ISSUE TITLE
Visual Studio guide

### ISSUE THREAD

**Issue by IeuanWalker** [puikinsh/Adminator-admin-dashboard#117]
<h1>Documentation issue</h1>

Hi,

Is it possible to have a guide of integrating this into Visual Studio for .net core razor pages.
I'm not a front end developer and not familiar with NPM and WebPack and how it works within visual studio.

Guide like this would be really useful - https://www.coderepo.blog/posts/building-elegant-applications-aspnet-core-mvc-2.1-coreui-2-bootstrap-4/

**Comment by AndreiCN** [comment]
We will be more than happy to add this in our documentation but we do not have plans in that direction for now since this is a frontend template. Thank you for the suggestion and good luck !
