### ISSUE TITLE
how to include html to html

### ISSUE THREAD

**Issue by mg4z** [puikinsh/Adminator-admin-dashboard#119]
<h1>Feature request</h1>

I need to have side bar and top bar on external file like sidebar.html , and include it to index.html when the page going to load.
I did it by .load() jquery but it just show the , when click on menu that have sub item, it dose not load.
I did it by https://www.npmjs.com/package/html-includes but it return error and the page on running.

**Comment by krzysiekpiasecki** [comment]
There are no plans to implement this feature.
