### ISSUE TITLE
how install Adminator-admin-dashboard

### ISSUE THREAD

**Issue by jeffersonor900** [puikinsh/Adminator-admin-dashboard#12]
when trying to follow the steps described, I do not load the css styles ... help pls

**Comment by jeffersonor900** [comment]
![image](https://user-images.githubusercontent.com/31443049/34110900-0d1c35d0-e3d6-11e7-95da-1b3a758978bb.png)

**Comment by kossa** [comment]
In your URL I see that you try to load the file directly from the folder, instead you have to deploy, and then launch the server(the urls are absolute not relative)

run : `npm run build` and open a server under the build folder

![image](https://user-images.githubusercontent.com/1175584/34334746-6c48deaa-e949-11e7-81fb-022d54a73762.png)

**Comment by alanjinqs** [comment]
@kossa Yep, I can run it through `npm run build`. But how can I deploy it to my server(With NGINX)? Which libraries are dependent?

**Comment by joseblanco77** [comment]
I run `npm run build` command, but it freezes after next lines:

![image](https://user-images.githubusercontent.com/26335965/34388372-d68cded2-eaf8-11e7-8c7e-d6e17ca92017.png)

I can get a compiled version? I don't want to use Admin LTE (ugly) or sb-admin (too simple) anymore.

**Comment by kossa** [comment]
@AlanJinqs you can upload only the build folder to your server

Otherwise the best way is to build and link your server directly to build folder

@joseblanco77 may be problem with node version

**Comment by joseblanco77** [comment]
@kossa thank you but it doesn't work. I just update my node from v6.11.3 to v9.2.1

Then I run the `npm install` and `npm run build` and still freezing at the same point.

**Comment by kossa** [comment]
@joseblanco77, got to top of command window you'll see the error

something like : 
![image](https://user-images.githubusercontent.com/1175584/34402525-64499f54-eba2-11e7-820f-0b075d7e0e5b.png)

For me it's freezing too, but I opened new window I launched a server and it everything works fine
![image](https://user-images.githubusercontent.com/1175584/34402788-4e662610-eba4-11e7-9819-354c54f6cf91.png)

**Comment by alanjinqs** [comment]
@kossa Thanks, but when I upload the build folder to my server, I can't load the CSS styles...It's same as load the src folder directly...

**Comment by kossa** [comment]
Point your server to directly to build folder, bcz the link to css are absolute ;)

**Comment by alanjinqs** [comment]
@kossa Thanks a lot :-)

**Comment by rahmatputrawiranata** [comment]
i just try to build somethink adminator but when i try using npm run dev this think happen to me
![image](https://user-images.githubusercontent.com/34281063/35025794-20514da0-fb7a-11e7-87e6-84f50cfeb439.png)

**Comment by rsagie** [comment]
Hi @rahmatputrawiranata I got the same error as you (happens on windows machines)
I resolved it with this:
open up a new cmd as administrator and run this command:
npm install --global --production windows-build-tools

Found the solution at  https://github.com/chjj/pty.js/issues/60

**Comment by danielpettifer** [comment]
Have finally got working.

Steps:
1 delete node_modules folder
2 $ npm install
3  $ npm run build
3.1 Fix all errors for dependencies that show up (from what I can see people are experiencing different issues here). Everything should show up green when all errors are fixed and you run $ npm build
4 $ webpack-dev-server --no-inline

**Comment by AndreiCN** [comment]
@jeffersonor900 does any of this solutions worked for you ?

**Comment by AndreiCN** [comment]
After "npm run dev" , load it on the server created by webpack "http://localhost:3000/index.html" and will work for sure, not just "http://0.0.0.0:3000/" or "http://127.0.0.1:3000" they are the same thing.

**Comment by w33haa2** [comment]
how do i implement this on a  laravel-based project??

**Comment by kossa** [comment]
Already done : https://github.com/kossa/laradminator

**Comment by rsuregar** [comment]
how to I add another plugin like select2.js? thank for advance

**Comment by kossa** [comment]
Here is an example for sweetalert 2

https://github.com/kossa/laradminator/blob/master/resources/assets/js/bootstrap.js#L37
https://github.com/kossa/laradminator/blob/master/resources/assets/js/sweetalert2/index.js

**Comment by HenriqueAssreuy** [comment]
How do i implement this on a asp.net mvc project?

**Comment by achilles03anil** [comment]
How do i implement this on a asp.net mvc project?

**Comment by cristinakity** [comment]
How do i implement this on a asp.net mvc project?

**Comment by Mrgove10** [comment]
How do i implement this on a asp.net mvc project?

**Comment by abhijeetc50** [comment]
How to add a new page?

**Comment by ghost** [comment]
How to get it in Angular project?

**Comment by mhfrough** [comment]
> How to get it in Angular project?

**Comment by Kukunin** [comment]
Instead of forking and modifying the project itself, it'd be cool to have an option to use it as dependency:

   yarn add adminator

 in css file

```sass
@import "adminator/src/assets/styles/index.scss"
```

in js flie

```js
import "adminator/src/assets/scripts/index";
```

**Comment by Kukunin** [comment]
Just in case someone has googled this issue. 

Successfully ran adminator on Phoenix framework (Elixir) with the following webpack 4:

My `package.json` dependencies:

```json
{
  "dependencies": {
    "adminator": "https://github.com/puikinsh/Adminator-admin-dashboard.git",
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.0",
    "copy-webpack-plugin": "^4.5.0",
    "css-loader": "^2.1.1",
    "mini-css-extract-plugin": "^0.4.0",
    "node-sass": "^4.12.0",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "sass-loader": "^7.1.0",
    "uglifyjs-webpack-plugin": "^1.2.4",
    "webpack": "4.4.0",
    "webpack-cli": "^3.3.2"
  }
}
```

`webpack.config.js`:

```js
const path = require('path');
const glob = require('glob');
const webpack = require('webpack');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = (env, options) => ({
  optimization: {
    minimizer: [
      new UglifyJsPlugin({ cache: true, parallel: true, sourceMap: false }),
      new OptimizeCSSAssetsPlugin({})
    ]
  },
  entry: {
      './js/app.js': ['./js/app.js'].concat(glob.sync('./vendor/**/*.js'))
  },
  output: {
    filename: 'app.js',
    path: path.resolve(__dirname, '../priv/static/js')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader']
      },
      {
        test: /\.scss$/,
        use: [
            MiniCssExtractPlugin.loader,
            "css-loader",
            "sass-loader"
        ]
      },
      {
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        exclude: /node_modules\/(?!(adminator)\/).*/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '../css/[name].[ext]'
            }
          }
        ],
      }
    ]
  },
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery',
      Popper: ['popper.js', 'default'],
    }),
    new MiniCssExtractPlugin({ filename: '../css/app.css' }),
    new CopyWebpackPlugin([{ from: 'static/', to: '../' }])
  ]
});
```

and a single line in `app.js`:

```js
import "adminator/src/assets/scripts/index";
```

**Comment by byron-perez** [comment]
Is it possible to add adminator to an existing laravel project?

**Comment by joseblanco77** [comment]
Of course!!

Just make a blade template with it!!

**Comment by Markuz1995** [comment]
Hello could you guide me how to implement the template in angular 8 or an example to consult?
