### ISSUE TITLE
can we use this on a react js app ?

### ISSUE THREAD

**Issue by hamdi-islam** [puikinsh/Adminator-admin-dashboard#120]
hi, thanks for the great theme it is really awesome !! i am trying to figure out how i can merge it into my React JS app but unfortunately I couldn't find my way through.

The steps I've done so far were to:
1- include the assets folder into my src folder
2- rename App.css to be App.scss
3- fill in App.scss with what's already in /assets/styles/index.scss
4- creating a dashboard component

The following screenshot shows how messy the page I get is, A little help would be much appreciated :) thank you
<img width="1278" alt="screen shot 2018-09-04 at 15 59 38" src="https://user-images.githubusercontent.com/18231944/45039448-9306a980-b05b-11e8-9d78-e61bcf7c7eb8.png">

**Comment by romeyng** [comment]
Did you ever make any progress with this? I need to do the same thing. I know there's a ton of dependencies in the node modules folder that would need to be included.

**Comment by krzysiekpiasecki** [comment]
@hamdi-islam Can you provide a screenshot from dev tools? It looks like the problem with css.

**Comment by krzysiekpiasecki** [comment]
@hamdi-islam It's a webpack application. To get the best support try to ask in forums for react developers. thanks.
