### ISSUE TITLE
Getting this error from Vendor.js file

### ISSUE THREAD

**Issue by LittleGyaani** [puikinsh/Adminator-admin-dashboard#122]
vendor.js:1 Uncaught Error: Syntax error, unrecognized expression: [href*="localhost"
    at Function.e.error (vendor.js:1)
    at e.tokenize (vendor.js:1)
    at e.compile (vendor.js:1)
    at vendor.js:1
    at PSEUDO (vendor.js:1)
    at _ (vendor.js:1)
    at e.compile (vendor.js:1)
    at e.select (vendor.js:1)
    at e (vendor.js:1)
    at Function.e.matchesSelector (vendor.js:1)

**Comment by danieljsc** [comment]
+1 that is happening in the demo provided in the Readme

**Comment by frostbites80** [comment]
Same issue here, has anyone found the solution to fix this?

**Comment by punitj1221** [comment]
> vendor.js:1 Uncaught Error: Syntax error, unrecognized expression: [href*="localhost"
> at Function.e.error (vendor.js:1)
> at e.tokenize (vendor.js:1)
> at e.compile (vendor.js:1)
> at vendor.js:1
> at PSEUDO (vendor.js:1)
> at _ (vendor.js:1)
> at e.compile (vendor.js:1)
> at e.select (vendor.js:1)
> at e (vendor.js:1)
> at Function.e.matchesSelector (vendor.js:1)

Would you please let me know where is this file I cannot find it. Also where you are getting the error (on which page)?

**Comment by sublimedatasys** [comment]
Hi @LittleGyaani Litt, @punitj1221, @frostbites80 

This error has been solved earlier. It is showing error due to the missing closing square brackets in src/assets/utils/index.js. Please take a new clone. Thank you!
