### ISSUE TITLE
How to add new page?

### ISSUE THREAD

**Issue by jack610191** [puikinsh/Adminator-admin-dashboard#123]
first, thanks to all developers in this project.
as following readme Deployment steps, I run this project successfully.
but, I would like to add new page in src.
I try to copy datatable.html as mytable.html for testing
I have tried rerun npm run build/npm run start.
but i seems mytable.html is not build.
I try to read package.json and webpack/config.js
but I still don't know what to do.
what did i miss and what should I do? thanks.

**Comment by jack610191** [comment]
Sorry, After search all issue. I found the solution.
Go to ./webpack/plugins/htmlPlugin.js then add new *.html files at array titles.
like this,
const titles = {
  ..omit
  '404': '404',
  '500': '500',
  'basic-table': 'Basic Table',
  'itemtable' : 'Item Table'	
};

Thanks for all developers again!

**Comment by krzysiekpiasecki** [comment]
@JackLin-Wei Please close this ticket as it has been resolved.
