### ISSUE TITLE
Usual CSS and JS files

### ISSUE THREAD

**Issue by Masoud180** [puikinsh/Adminator-admin-dashboard#126]
Hi
I'm not familiar with node.js, npm, scss etc.
How can I have this project with the usual CSS and JS files imported?
Is there any link to download this project with the usual CSS and JS files?
Thanks in advanced

**Comment by Gr6** [comment]
bump

**Comment by arslanahmd** [comment]
bump

**Comment by sublimedatasys** [comment]
Hi @Masoud180 ,
We do not have this template with usual CSS and JS, but @MysteryDash has added a link to the code. Please review issue #145 for the same. Here is the URL.
