### ISSUE TITLE
Wrong color hex.

### ISSUE THREAD

**Issue by zjbarg** [puikinsh/Adminator-admin-dashboard#127]
Wrong color #d3c4a in assets/styles/spec/settings/brandColors.scss line:1111 [Link](https://github.com/puikinsh/Adminator-admin-dashboard/blob/e7e1efe86f643a058cd567bdd77a6a97178919dd/src/assets/styles/spec/settings/brandColors.scss#L1111)
Missing one character.

**Comment by krzysiekpiasecki** [comment]
@ZaidBarghouthi  Thanks for your report :+1:
