### ISSUE TITLE
The left menu is cut off when it is higher than the screen width

### ISSUE THREAD

**Issue by jakimov** [puikinsh/Adminator-admin-dashboard#129]
<h1>Bug report</h1>

# Current behavior
The left menu is cut off when it is higher than the screen height

# Expected behavior 
The user should be able to scroll the left menu up and down to access all menu links

**Comment by sublimedatasys** [comment]
Hi @jakimov ,

This works fine. Please click on the “expand icon” under the menu item as it has a sub-menu item and which will allow you to scroll side menu.  Hope this helps. Please let us know if still have any questions for us. Thank you!
