### ISSUE TITLE
Sort icons not showing in datatable? 

### ISSUE THREAD

**Issue by mirkr13** [puikinsh/Adminator-admin-dashboard#130]
<h1>Bug report</h1>
<h1>Feature request</h1>
<h1>Support request</h1>
<h1>Documentation issue</h1>

# Current behavior

# Expected behavior 

# Environment
Platform: 
Browser: 

For building issues:
Node:           
NPM:

**Comment by sublimedatasys** [comment]
Answer=>Hi @mirkr13 ,

Thank you for pointing out the bug, This bug is fixed and will be available in the next release.
