### ISSUE TITLE
is it usable with Django?

### ISSUE THREAD

**Issue by yanadhorn** [puikinsh/Adminator-admin-dashboard#131]
i am looking for a theme like this but it will be front end for my website. i like theme but will modified some. but i am not familiar with node js then i dont know how to modify with django.

<h1>Bug report</h1>
<h1>Feature request</h1>
<h1>Support request</h1>
<h1>Documentation issue</h1>

# Current behavior

# Expected behavior 

# Environment
Platform: 
Browser: 

For building issues:
Node:           
NPM:

**Comment by nstudt** [comment]
Python/Django would be the equivalent of javascript/node.js and are server-side technologies. What you have presented is html/css. To make it dynamic, you would use javascript.
It would be helpful for you to do some reading on those subjects.

**Comment by krzysiekpiasecki** [comment]
> is it usable with Django?

Yes, It's usable. This repository contains a server which serves a frontend content. You can develop it and make XHR requests to your backend services.

On the other side, you can extract from this repository the whole HTML structure and javascript dependencies - listed in package.json - and integrate all in your Django App. It's also possible. Here you have a working example incorporating Adminator into a Symfony Framework (PHP). https://github.com/krzysiekpiasecki/Symfonator

If you have no more questions please close this ticket.

**Comment by ccrvlh** [comment]
I couldn't figure out how to apply the static to my Flask project.
I included all assets to my local assets folder, and the .html to my templates folder (jinja templates), but it doesn't show the page correctly neither tells me which packages are missing in console.
Any other resource that help implement only the front end aspect of this template with Flask backend?
Thanks a lot.
