### ISSUE TITLE
Title in Topbar

### ISSUE THREAD

**Issue by matiasmascioto** [puikinsh/Adminator-admin-dashboard#133]
<h1>Support request</h1>

How can I insert a centered title in Topbar (_header navbar_)?

![captura](https://user-images.githubusercontent.com/5489787/48202856-d2e05a80-e344-11e8-8b57-e6000daecbce.JPG)

Thanks.

**Comment by krzysiekpiasecki** [comment]
I hope you've found a solution. You can get many approaches to achieve centered title in Topbar, but in general you have to refactor html structure and add css styles.

One of the solutions is using the absolute positioning for a new layer - relatively to parent layer.
```
<div class="header navbar">
    <div class="header-container">
        <ul class="nav-left">...</ul>
        <div class="text-align:center" style="
            position: absolute;
            width: 100%;
            text-align: center;
            line-height: 65px;">
            TITLE HERE
        </div>
        <ul class="nav-right">...</ul>
    </div>
</div>
```

@matiasmascioto If you resolved your problem, please close this ticket. Thanks.

**Comment by krzysiekpiasecki** [comment]
@puikinsh Please close this ticket due to author inactivity
