### ISSUE TITLE
Don't get the demo style

### ISSUE THREAD

**Issue by itxchandan** [puikinsh/Adminator-admin-dashboard#135]
Hello,

I followed all the steps but don't get the style as a demo. Only content show. See the screenshot.

![image](https://user-images.githubusercontent.com/17069784/48347789-51baf780-e6a5-11e8-9033-2394c37be3b4.png)

Thanks,
Chandan

**Comment by ghost** [comment]
Please ensure you install all the npm dependencies.

**Comment by dfmurillo** [comment]
Hi, I have the same problem, I have already installed all dependencies, but on **npm run dev** i get this error:
![image](https://user-images.githubusercontent.com/1246053/52801085-20a6e600-304b-11e9-91c9-b02af05ab8c8.png)

Platform: macOS High Sierra
Browser: Chrome

For building issues:
Node: 11.2.0
NPM: 6.5.0

**Comment by webgrill** [comment]
Can you load html version? To use it without npm

**Comment by mreduar** [comment]
Any solution to this problem? I am presenting the same error

**Comment by sublimedatasys** [comment]
Hi @chandanndeep ,

It seems that node-sass is not properly installed as a dependency in node-module and npm has some permission issue with node-sass. Hence, please try once by running the following command. Also, clear site data

npm install --save-dev  --unsafe-perm node-sass

Hi @dfmurillo ,
 I tried to reproduce the same error and it seems that there is an issue with dependencies. Please make sure there should not be any error and vulnerability with the npm installation. I followed the same and it worked for me.

**Comment by itxchandan** [comment]
Thank you @sublimedatasys.
