### ISSUE TITLE
Sidebar link active doesn't show dot

### ISSUE THREAD

**Issue by cgmerida** [puikinsh/Adminator-admin-dashboard#136]
<h1>Bug report</h1>

The style the sidebar.scss has a class .active:before but it is not working.

# Environment
Platform: windows 10
Browser:  chrome

For building issues:
Node: v10.11.0     
NPM: v6.4.1

**Comment by MrMoosti** [comment]
I have the same issue, when building the project with

> npm run dev

The dots don't work but when:

> npm run preview

the dots show up.

**Comment by MrMoosti** [comment]
I made a pull request for this issue, a quick fix: #155 It needs to be pulled into the master by one of the contributors.

**Comment by puikinsh** [comment]
Fixed on #155 

Thank you @MrMoosti for making this happen!
