### ISSUE TITLE
Problem with the active menu

### ISSUE THREAD

**Issue by cgmerida** [puikinsh/Adminator-admin-dashboard#137]
https://github.com/puikinsh/Adminator-admin-dashboard/blob/987c278fb854a38c76f4728af211314c065bf727/src/assets/scripts/sidebar/index.js#L55

I had a problem with the dot in the active link. the filter always returns false. so I change the code from:

`return pattern === (window.location.pathname).substr(1);`

to 

`return pattern === window.location.href;`

Hope it helps

**Comment by krzysiekpiasecki** [comment]
@cgmerida thanks.
