### ISSUE TITLE
Remove self invoking functions

### ISSUE THREAD

**Issue by Luc-cpl** [puikinsh/Adminator-admin-dashboard#138]
<h1>Feature request</h1>

When I move from dashboard to another page and back to dashboard in a webapp whithout refresh the page, functions like the search button and the sidemenu button stop working and whe could not restart.

The best way that i found to enable this is change all the exported self invoke functions for normal functions (just removing the "()" at the end of function), this way is possible import the file and call the function when needed.

To mantain the behavior, I just set one self invoking function at the main index.js file and start all functions on that function.

The main index.js stays like this:
```
import mansory from './masonry';
import charts from './charts';
import popover from'./popover';
import scrollbar from './scrollbar';
import search from './search';
import sidebar from './sidebar';
import skycons from './skycons';
import vectorMaps from './vectorMaps';
import chat from'./chat';
import datatable from './datatable';
import datepicker from './datepicker';
import email from './email';
import fullcalendar from './fullcalendar';
import googleMaps from './googleMaps';
import utils from './utils';

export default (function(){
  Mansory()
  Charts()
  Popover()
  Scrollbar()
  Search()
  Sidebar()
  Skycons()
  VectorMaps()
  Chat()
  Datatable()
  Datepicker()
  Email()
  Fullcalendar()
  GoogleMaps()
  Utils()
}())
```

**Comment by sublimedatasys** [comment]
Hi @Luc-cpl ,
Thanks for your valuable suggestion and we will consider your methodology in an upcoming release.
