### ISSUE TITLE
Trying to delete some html file's

### ISSUE THREAD

**Issue by GioUrnau** [puikinsh/Adminator-admin-dashboard#139]
Hello!
I'm trying to delete some html files from the project but i can't. When i do, the project doesn't compile. What i have to do?
Tanks and congratulations for the job!

**Comment by GioUrnau** [comment]
Someone?

**Comment by krzysiekpiasecki** [comment]
Hi,

To remove page follow up: 

1. Open ```./webpack/plugins/htmlPlugin.js``` 
2. Remove page name from const titles in ```htmlPlugin.js```
3. Remove html page from ```./src```
4. Remove assets from ```./src/assets``` which belongs only to deleted page.

You can add a new page  reverting this list and replacing of course remove with a verb add.
