### ISSUE TITLE
Can someone provide a build of this with static HTML, CSS and JS unminified

### ISSUE THREAD

**Issue by designforhumans** [puikinsh/Adminator-admin-dashboard#145]
This would help people who just want to get going with the template without having to install node and other dependencies. If you could include this in the main source repo that would be awesome and would save lots of people lots of time.

Thank you from the bottom of my heart ❤️

**Comment by jahanzebsh** [comment]
Yeah i need that too :-) :+1:

**Comment by MysteryDash** [comment]
Here's a build I just made (I'm leaving the time in the name).
Not unminified, but if I get time later today I'll do it and update this post. There are some files with seemingly random names that are bothering me so it'd be good to have them renamed as well.

[Adminator 17-02-2019 18-41 (Paris Time).zip](https://github.com/puikinsh/Adminator-admin-dashboard/files/2873221/Adminator.17-02-2019.18-41.Paris.Time.zip)
Note: this build was made using the latest commit as of today: 987c278.

EDIT: Unbundling the JS and CSS seems like hell. This kinda sucks, as it makes integrating this template unnecessarily complex.

**Comment by jahanzebsh** [comment]
wow thats great , thanks alot dear , it does worth alot.

**Comment by Prem18mca** [comment]
HOw can i use in server can you give me with link and script inside of every html file

**Comment by KilianB** [comment]
@MysteryDash  can you give us a quick instruction on how to generate the bundle ourselves? There are a few unnecessary js files which can be stripped.

I am currently getting used to webpack and am trying to figure out how to bundle a production version. There are quite a few config files flying around.

**Comment by MysteryDash** [comment]
I just followed the instructions that are in the Readme of this repository.
I'm far from being a webpack expert, and if I were I would have removed the whole "pack" part of webpack.

**Comment by bci24** [comment]
It will be nice to have the separate js files and  css as well. For example i would like to use this template in a laravel project :)

**Comment by TCB13** [comment]
+1 on this!

**Comment by rlphnger** [comment]
Would really appreciate this a lot. Simpler to work on, and easier to simplify.

**Comment by bkkrishna** [comment]
> It will be nice to have the separate js files and css as well. For example i would like to use this template in a laravel project :)

Better have a look at [this](https://github.com/puikinsh/Adminator-admin-dashboard/issues/60)

**Comment by arriagadadev** [comment]
In [this repository](https://github.com/arriagadadev/Adminator-admin-dashboard-laravel) you can see this template in a laravel 6.x (blade) adaptation.
In the "public" folder you can get the javascript and css files not minified too.

**Comment by jepperaskdk** [comment]
I started a branch for prebuilding minified and unminified static assets here: https://github.com/puikinsh/Adminator-admin-dashboard/tree/feature/prebuild

Will be built and attached to each release.

**Comment by jepperaskdk** [comment]
From 2.0.3 we prebuild both minified and unminified static assets for each release: https://github.com/puikinsh/Adminator-admin-dashboard/releases

You can build these yourself as well, using `npm run release:unminified` or `npm run release:minified`.
