### ISSUE TITLE
iPad - not working

### ISSUE THREAD

**Issue by clarity-ltd-dw** [puikinsh/Adminator-admin-dashboard#148]
<h1>Bug report</h1>

To use the theme on an iPad
# Current behavior

When opening my site (https://essex-test.cycleready.co.uk) I'm left with a spinning dialog - the same happens when I use the official Adminator URL (https://colorlib.com/polygon/adminator/index.html) too.
# Expected behavior 

Show the log in page

# Environment
Platform: iOS (iPad) v9.3.5 (13G36)
Browser: Chrome

For building issues:
Node:           
NPM:

**Comment by puikinsh** [comment]
Since there is no way to test it we no longer support that old devices. Sorry for the inconvenience.
