### ISSUE TITLE
how do I Change world map to Country map ?

### ISSUE THREAD

**Issue by dineshdedhia** [puikinsh/Adminator-admin-dashboard#151]
<h1>Bug report</h1>
<h1>Feature request</h1>
<h1>Support request</h1>
<h1>Documentation issue</h1>

# Current behavior

# Expected behavior 

# Environment
Platform: 
Browser: 

For building issues:
Node:           
NPM:

**Comment by jepperaskdk** [comment]
1. Go here and download the country you want to show: http://jvectormap.com/maps/countries/
2. Place the file in `src/assets/scripts/vectorMaps`
3. Import the file in the top of `src/assets/scripts/vectorMaps/index.js`, e.g. like: `import './jquery-jvectormap-dk-mill.js';`.
4. In the same file, change `map: 'world_mill',` to `map: 'dk_mill',` (replace dk with the country code).
5. Check the result (perhaps with a restart of the dev-server):
![image](https://user-images.githubusercontent.com/10128260/60761540-15307780-a04b-11e9-9c0a-65ebcb70d714.png)
