### ISSUE TITLE
How do I add Custom HTML File ?

### ISSUE THREAD

**Issue by dineshdedhia** [puikinsh/Adminator-admin-dashboard#152]
<h1>Bug report</h1>
<h1>Feature request</h1>
<h1>Support request</h1>
<h1>Documentation issue</h1>

# Current behavior

# Expected behavior 

# Environment
Platform: 
Browser: 

For building issues:
Node:           
NPM:

**Comment by krzysiekpiasecki** [comment]
You can add a new html file, according to #139.
