### ISSUE TITLE
Date pickers for time ranges

### ISSUE THREAD

**Issue by Kukunin** [puikinsh/Adminator-admin-dashboard#156]
<h1>Feature request</h1>

As for the data dashboard, I wonder why there is no date selectors for time intervals: for example I want to get data for previous year or calculate a custom indicator for last N months.

Also, on forms page I didn't found any input with date selector (calendar or so).

I believe, it's pretty relevant feature to have.

You can take a look here what I mean: https://demo.baremetrics.com/

![the demo](https://imgur.com/xxjBMjJ.png)

Thanks

**Comment by Kukunin** [comment]
I found that git version contain bootstrap-datepicker, and it's on the forms.html page. There is an old page on demo https://colorlib.com/polygon/adminator/forms.html so I didn't find it at first glance.

**Comment by krzysiekpiasecki** [comment]
@Kukunin  thanks

**Comment by sarowerj** [comment]
how can i use datepicker with latest theme?
