### ISSUE TITLE
ASP.NET MVC Support 

### ISSUE THREAD

**Issue by moumen100** [puikinsh/Adminator-admin-dashboard#158]
How can we use this template in ASPNET MVC 5.0 Project

**Comment by achilles03anil** [comment]
Any updates in ASPNET intregration ?

**Comment by jepperaskdk** [comment]
I'm not sure how to integrate the *.cshtml files generally, but you can check out this link which seems to achieve it: https://medium.com/@jonjam/combining-webpack-with-asp-net-mvc-5-a5bd07c49d0b

Microsoft also offers [UseWebpackDevMiddleware](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webpackdevmiddleware.usewebpackdevmiddleware?view=aspnetcore-2.2).

**Comment by krzysiekpiasecki** [comment]
This node application is not provided for ASP.NET architecture.
