### ISSUE TITLE
Can I remove footer copyright text.

### ISSUE THREAD

**Issue by saileshkush95** [puikinsh/Adminator-admin-dashboard#159]
Sorry for this stupid questions. I'm quite unfamiliar about MIT license. That why I'm asking this questions. Can I replace footer text " Copyright © 2017 Designed by Colorlib. All rights reserved." by some thing like this "Copyright © somethings| All rights reserved.

**Comment by sublimedatasys** [comment]
Hi @saileshkush95 ,
Please read license policy.
https://github.com/puikinsh/Adminator-admin-dashboard/blob/master/README.md#license
