### ISSUE TITLE
Top menu layout please  &   less waste of screen space.

### ISSUE THREAD

**Issue by weedkiller** [puikinsh/Adminator-admin-dashboard#16]
Hello, I like this BS theme, any chance we can get a top menu layout please.

![image](https://user-images.githubusercontent.com/21086190/34130581-5c323bf2-e416-11e7-9a6e-cf0da6a71e5b.png)

![image](https://user-images.githubusercontent.com/21086190/34130644-9de7dec6-e416-11e7-8f7a-e47952a6ca66.png)

Thanks

**Comment by puikinsh** [comment]
Irrelevant for Github issue tracking. 

You can try asking on StackOverflow or other developer forums.
