### ISSUE TITLE
Does the template support multiple select dropdown?

### ISSUE THREAD

**Issue by AhSem** [puikinsh/Adminator-admin-dashboard#160]
I can't find an example for multiple select dropdown. Any idea how to do it?

**Comment by krzysiekpiasecki** [comment]
Add ```multiple``` attribute on html select html.

**Comment by sublimedatasys** [comment]
Hi @AhSem ,

This template doesn’t support multi-select drop-down. Please refer below URL, it shows how to implement a multi-select drop-down. In the upcoming release, we may add a multi-select drop-down.

https://mdbootstrap.com/docs/jquery/forms/multiselect/
