### ISSUE TITLE
Set static path for font *.woff or *.woff2

### ISSUE THREAD

**Issue by khrlimam** [puikinsh/Adminator-admin-dashboard#162]
<h1>Bug report</h1>

I have problem to use the built asset for laravel project. The issue is *woff and *.woff2 link file always dinamic. For example I have url given like : app.com/parent/child the generated url for *.woff and *.woff2 is /parent/*.woff and /parent/*.woff2. How do I set the static path url for the *.woff files? For example I store the *.woff and *.woff2 files on specific directory and the generated url always pointed to that directory.

Thanks!

# Environment
Platform: Mac OS
Browser: Brave, Safari, Chrome
Node:           v10.15.0
NPM:          6.4.1

**Comment by krzysiekpiasecki** [comment]
Closed due to inactivity.
