### ISSUE TITLE
All code

### ISSUE THREAD

**Issue by TrippyFx** [puikinsh/Adminator-admin-dashboard#163]
HTML not working correctly

**Comment by krzysiekpiasecki** [comment]
Please provide more details.

**Comment by TrippyFx** [comment]
So I have no idea how to set this up and I kind of need help. I tried to
look at the html but it’s not loading the whole page only pictures and
text. I don’t know what app to use to set this up. I need help

**Comment by krzysiekpiasecki** [comment]
You have to follow installation instruction at README.
