### ISSUE TITLE
Not able to close a modal (dialog)

### ISSUE THREAD

**Issue by danieldestro** [puikinsh/Adminator-admin-dashboard#164]
I have a button that opens up a modal dialog box so the user can say Yes / No to a question.

```
<!-- button -->
<button id="btn123" type="button" class="btn btn-block cur-p btn-primary" data-toggle="modal" data-target="#modalConfirm">Update</button>
```

```
<!-- modal -->
<div id="modalConfirm" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalConfirmLabel" aria-hidden="true">
...
  <div class="modal-footer">
    <button id="btn-no" type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
    <button id="btn-yes" type="button" class="btn btn-primary">Yes</button>
  </div>
...
</div>
```

However, when writing a javascript to handle the user response (yes/no button) I cannot hide/close the modal dialog.

When I run the code below it gives me a JS error saying that modal is not a valid function.

`$('#modalConfirm').modal('hide');`

Instead, if I use the code below, the modal window get hidden but a gray layer still remain visible and the screen cannot be used anymore (refresh is required).

`$('#modalConfirm').hide();`

To overcome this sittuation I had to download and add jquery (3.4.1) and bootstrap (4.3.1) and add the javascript files to my html.

It requires this code to show the dialog.

`$('#modalConfirm').modal('show');`

Now, modal('hide'); will close the modal and work fine.

However, the user menu is no longer working, it does not opens up the user menu (top). Also the former button to show the dialog is not working anymore (I had to use jquery for this).

What I am doing wrong?

I am bit confused why Adminator does not use jquery and boostrap the same way as many other templates do.

**Comment by sublimedatasys** [comment]
Answer=>Hi @danieldestro ,

Please do refer #69 this will help you. This template uses npm for dependency and package management, hence the approach to use bootstrap and jquery is different. In order to use jquery and bootstrap, you just need to import them as a dependency in your js file and it will work fine.

Thank you.
