### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by qcode-1** [puikinsh/Adminator-admin-dashboard#166]
When i access the index.htm page, it seems broken...? How do i preview the project after cloning? I suppose it is purely HTML, CSS and JS...

**Comment by arkarwmh** [comment]
Exactly. I also cannot run. I thought I'm downloading a "HTML Template" but ended up realising it's installation is even more complicated than actual Backend Developments. I can neither install nor run this.

**Comment by sublimedatasys** [comment]
Hi @qcode-1, @arkarwmh ,

Please make sure that you are following the all the instructions mentioned in the following URL

https://github.com/puikinsh/Adminator-admin-dashboard/blob/master/README.md#getting-started .

Please let me know if you are still facing any further issues.
