### ISSUE TITLE
How to include custom .js files to new .html pages

### ISSUE THREAD

**Issue by taherrera** [puikinsh/Adminator-admin-dashboard#169]
Hey,

I can add new html pages by following #139 

However, I need to add custom javascript behaviour to these new files. I tried adding javascript files following the structure in src/assets/scripts and then adding the import in src/assets/scripts/index.js, however I do not know how to link the html file to the javascript files/folder.

Thanks for the help !

**Comment by superevvy** [comment]
I have a similar issue. Is anyone able to help?

**Comment by devleaks** [comment]
Yes, a couple of examples of inclusion of external libraries would be a must.
For example leafletjs instead of google map, or something similar.
Otherwise, the dashboard is really simple and nice. Thank you.

**Comment by DPTeamMember** [comment]
Hello @devleaks @taherrera @superevvy 

The steps followed by @taherrera to create a new js file in the template are correct, however, linking of HTML file to the javascript files/folder is done by webpack itself. We set everything in the template by which webpack creates a js bundle and adds it to HTML files.
For more information, you can read how webpack manages output here - https://webpack.js.org/guides/output-management/
Closing this issue, for now, feel free to reopen if have any question or issue

Thank you.
