### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by neosin** [puikinsh/Adminator-admin-dashboard#17]
I tried the official demo on my Samsung galaxy s8+ and it does not display responesively. Everything shrinks in the browser and it is impossible to read or use.
Is the demo just not built to work on small screens?

**Comment by kossa** [comment]
The same issue on iphone 5s, but working fine on browser

**Comment by sohal07** [comment]
noticed same.....and it doesn't even scroll properly on iphone 7

**Comment by rbrlortie** [comment]
Is this fixed? I'm also seeing everything as really small text while in mobile mode. 

What's strange is that if I make my desktop browser smaller I get the mobile styles. But on the mobile, I get really small desktop styles instead. 

On the official demo website.


![image](https://user-images.githubusercontent.com/23345449/50110568-9851c380-0208-11e9-8013-e0668b5ddc4d.png)
