### ISSUE TITLE
Info popup/modal

### ISSUE THREAD

**Issue by jepperaskdk** [puikinsh/Adminator-admin-dashboard#172]
Does the theme support any kind of info popup/modal, e.g. like the Material "Snackbar": https://material.io/components/snackbars/#usage

**Comment by DPTeamMember** [comment]
Hello @jepperaskdk 

In the template under the UIElement widget, we do have a bootstraps popup/modal. 
Currently, the template does not support material or Snackbar, will try to include this in the next possible release.

Thank you.
