### ISSUE TITLE
how to run have video ?

### ISSUE THREAD

**Issue by ahasantech** [puikinsh/Adminator-admin-dashboard#174]
Dear all, i am beginner, i want to use Adminator-admin-dashboard theme , have any video for installation process. or any one give me suggest step by step...
also error npm installation. 
![eeeeeeeeeee](https://user-images.githubusercontent.com/61349388/75440690-aacf9d00-5975-11ea-9882-d779b08b75e5.PNG)
![ccccc](https://user-images.githubusercontent.com/61349388/75440711-b4f19b80-5975-11ea-9d41-93f04b041b5c.PNG)

**Comment by krzysiekpiasecki** [comment]
Just follow `Installing & Local Development` of `README` file. BTW your screenshot show, that you haven't installed git properly or just git is not on the path.
