### ISSUE TITLE
Some functions not working again.

### ISSUE THREAD

**Issue by VirtualChords** [puikinsh/Adminator-admin-dashboard#178]
Hi, good day to u. While I really give a massive thumbs up to those who work on this project, I encountered an issue. After downloading, installing and running the project, it all worked fine, however later on things really stopped working. I'm an angularjs user (i.e. angular 1.x), and I don't know, I'm not sure, but I think it was at the point of loading the pages asynchronously with the partial view in angularjs (ng-view) that this occurred.

The things that are not working are:
1. The weather and the full calendar no longer display.
2. The menu button at the top left of the page no longer toggles the slide out menu.
3. The togglers in the email when resized, do not worƙ.
4. The scrollbar in the email list is hidden.

When I open my console in the browser, if I click anything whatsoever, I get error messages that reoccur. An error of that has to do with cx cy something in vector maps or so.

Pls I need assistance, anyone.

**Comment by krzysiekpiasecki** [comment]
Probably you're right. You have to initialize scripts when DOM content exists and is ready. No chance to help you following your issue.

**Comment by VirtualChords** [comment]
Could there be any way of doing this as I'm not used to webpack ... I tried some search but I wasn't understanding anything

**Comment by krzysiekpiasecki** [comment]
Wrap js scripts within a function and then execute it after a content has been loaded.
