### ISSUE TITLE
facing issues while integrating with angular 9

### ISSUE THREAD

**Issue by prashant-93** [puikinsh/Adminator-admin-dashboard#179]
`{
  "name": "dashboard",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.1",
    "@angular/common": "~9.1.1",
    "@angular/compiler": "~9.1.1",
    "@angular/core": "~9.1.1",
    "@angular/forms": "~9.1.1",
    "@angular/platform-browser": "~9.1.1",
    "@angular/platform-browser-dynamic": "~9.1.1",
    "@angular/router": "~9.1.1",
    "bootstrap": "^4.0.0",
    "brand-colors": "^2.1.1",
    "firebase": "^7.7.0",
    "jquery": "^3.4.1",
    "ngx-toastr": "^12.0.1",
    "perfect-scrollbar": "^1.5.0",
    "popper.js": "^1.12.6",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.1",
    "@angular/language-service": "~9.1.1",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
`

I am facing issue while integration of side menu drop downs, in which you have used 
`<a class="dropdown-toggle" href="javascript:void(0);"></>`

and angular is not supporting this and when i change this data-toggle CSS breaks.

Kindly help

**Comment by krzysiekpiasecki** [comment]
What exactly Angular is not supporting? Could you provide us an error output?

**Comment by coinlaundryindia** [comment]
Hi,

I am trying to set this UI into my Angular 9 aplication and i am not able to get it running.

I have included bootstrap, style.css, vendor.js and bundle.js

Errors:
```
bootstrap:142 Uncaught TypeError: Cannot read property 'bind' of undefined
    at bootstrap:142
    at bootstrap:150
(anonymous) @ bootstrap:141
(anonymous) @ bootstrap:150
polyfills.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function
    at polyfills.js:1
(anonymous) @ polyfills.js:1
styles.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function
    at styles.js:1
(anonymous) @ styles.js:1
vendor.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function
    at vendor.js:1
(anonymous) @ vendor.js:1
main.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function
    at main.js:1
(anonymous) @ main.js:1
```
Thanks,
Mohan

**Comment by coinlaundryindia** [comment]
> Hi,
> 
> I am trying to set this UI into my Angular 9 aplication and i am not able to get it running.
> 
> I have included bootstrap, style.css, vendor.js and bundle.js
> 
> Errors:
> 
> ```
> bootstrap:142 Uncaught TypeError: Cannot read property 'bind' of undefined
>     at bootstrap:142
>     at bootstrap:150
> (anonymous) @ bootstrap:141
> (anonymous) @ bootstrap:150
> polyfills.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function
>     at polyfills.js:1
> (anonymous) @ polyfills.js:1
> styles.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function
>     at styles.js:1
> (anonymous) @ styles.js:1
> vendor.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function
>     at vendor.js:1
> (anonymous) @ vendor.js:1
> main.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function
>     at main.js:1
> (anonymous) @ main.js:1
> ```
> 
> Thanks,
> Mohan

Adding more to my question, after adding vendor.js and bundle.js my <app-root></app-root> becoming empty

**Comment by krzysiekpiasecki** [comment]
@coinlaundryindia ASFAIK you can't just include compiled bundles into your Angular project. You have to import template source files and build all once again.
