### ISSUE TITLE
JS issue in the console

### ISSUE THREAD

**Issue by kossa** [puikinsh/Adminator-admin-dashboard#19]
If you open : https://colorlib.com/polygon/adminator/index.html and you check the console you'll see 

![image](https://user-images.githubusercontent.com/1175584/34334770-a18ca312-e949-11e7-9988-51495d17e456.png)

**Comment by avinassh** [comment]
related https://github.com/puikinsh/Adminator-admin-dashboard/issues/11

**Comment by ghost** [comment]
The first error was solved in the last commit, the others are caused when the scale parameter of jvectormaps is NAN. I was able to find out that scale becomes NAN when the "jvectormap-container" div's width become 0px, that triggers an zero by zero division which results in NAN.

To fix this I edited the "jquery-jvectormap.min.js" file to add a verification for the zero width.

`/**
   * Synchronize the size of the map with the size of the container. Suitable in situations where the size of the container is changed programmatically or container is shown after it became visible.
   */
  updateSize: function(){
    this.width = this.container.width();
    this.height = this.container.height();
	if(this.width != 0){
    this.resize();
    this.canvas.setSize(this.width, this.height);
    this.applyTransform();
	}
  },`
That is just a hack, to fix it definitely we need to find why sometimes the container width becomes zero.
P.S.: I'm using jvectormap-next.

**Comment by kossa** [comment]
Thank you :)
