### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by rbiq** [puikinsh/Adminator-admin-dashboard#193]
Can you please update to latest Babel version? There were build errors when I ran npm start

**Comment by tomas789** [comment]
Hmm .. I'm not a maintainer of this project but I'm pretty sure s/he will ask you for more details. Like what was the error message, what did you do exactly, does that happen on current master, ... You know. The usual stuff. ;)

**Comment by DPTeamMember** [comment]
Hello @rbiq 

We have updated the template with the latest Babel version and other Webpack and its related dependencies.
Please review the latest release.  closing the issue for now, if you still face the error feel free to reopen the issue and share the error.

Thank you
