### ISSUE TITLE
Error: pngquant failed to build, make sure that libpng-dev is installed

### ISSUE THREAD

**Issue by jrichardsz** [puikinsh/Adminator-admin-dashboard#196]
# Current behavior
npm install throws an error

```
> pngquant-bin@4.0.0 postinstall /tmp/workspace/Adminator-admin-dashboard/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/tmp/workspace/Adminator-admin-dashboard/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/tmp/workspace/Adminator-admin-dashboard/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

# Expected behavior 
npm install must work

# Environment
Platform: ubuntu

For building issues:
Node:           10
NPM:          6.9.0

# Fix

`apt-get install libpng-dev` but what if I cant install this or my s.o does not support it?

**Comment by DPTeamMember** [comment]
Hello @jrichardsz 

We have updated the template with webpack 5 which minimizes the OS differences and dependencies.
Please check the new release.

Thank you.

**Comment by jepperaskdk** [comment]
Closing, please let us know if you continue to see this error.
