### ISSUE TITLE
top right corner's dropdown click event doesn't work if jquery is enabled in HTML template

### ISSUE THREAD

**Issue by TareqMonwer** [puikinsh/Adminator-admin-dashboard#205]
<h1>Bug report</h1>

After running build, when I add Jquery file at the bottom, the top right corner's dropdown menu's click event doesn't show menu items. I tried commenting out the jquery file, it starts working properly.

Platform: Manjaro KDE
Browser: Firefox. Chrome

![image](https://user-images.githubusercontent.com/33314452/103174592-ab82d980-488d-11eb-81f8-0928ec915dfd.png)

**Comment by DPTeamMember** [comment]
Hello @TareqMonwer 

please check for the jquery version compatibility, this may occur due to the version mismatch of the Jquery file you are using.
or you can try adding jquery before the main.js script.

Thank you.

**Comment by TareqMonwer** [comment]
Since I tried it long ago, I forgot the workaround :( We better close this issue. Thanks for your tips.
