### ISSUE TITLE
Problem in Build and Use

### ISSUE THREAD

**Issue by shpsyte** [puikinsh/Adminator-admin-dashboard#21]
Can I use this template in a simple HTML project?
I want to generate the template in HTML5 (to export to .Net Core) but I can not use or generate the final CSS files.

The command "npm run build" hangs and does not exit the screen below.

![screenshot_20171227085119](https://user-images.githubusercontent.com/3891610/34379657-86e47dd2-eae3-11e7-8ebe-089cc11d57f4.png)

**Comment by avinassh** [comment]
This is a known issue and not really a bug - https://github.com/puikinsh/Adminator-admin-dashboard/issues/7

**Comment by shpsyte** [comment]
Este e-mail foi desativado.
  
 Para suporte técnico clique no endereço abaixo
 https://desk.zoho.com/portal/iscosistemas/home

**Comment by shpsyte** [comment]
Ok, tks.
