### ISSUE TITLE
Bootstrap selectpicker not working

### ISSUE THREAD

**Issue by nor1c** [puikinsh/Adminator-admin-dashboard#23]
Hello,
I want to use bootstrap selectpicker (https://silviomoreto.github.io/bootstrap-select/examples/) with data-live-search attribute, but the options doesn't appear in the selection.

I tried to change the bootstrap version, it runs but the size of the button and text becomes very small. I think it's clashing with the bootstrap that's in bundle.js.

**Comment by anthonycha** [comment]
Any help here?
