### ISSUE TITLE
Original author attribution

### ISSUE THREAD

**Issue by BlazerYoo** [puikinsh/Adminator-admin-dashboard#248]
Hi, I have a question. Can I add a separate page on my website/app that is dedicated for listing all original sources (including Copyright © 2019 Designed by [Colorlib](https://colorlib.com/). All rights reserved.) and remove the footer at the bottom of the page?

![image](https://user-images.githubusercontent.com/69565038/118380767-5b917e80-b5b2-11eb-9a84-61c830e36d44.png)

Thanks in advance.

**Comment by jepperaskdk** [comment]
@puikinsh What's the take on this? The license allows for modification, e.g. removing the footer completely, so it just requires that the LICENSE is part of the source-code when using the theme?

**Comment by puikinsh** [comment]
@jepperaskdk Yes, you are absolutely right on this one.
