### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by kossa** [puikinsh/Adminator-admin-dashboard#25]
Any idea how to do it ?

**Comment by puikinsh** [comment]
Be my guest to create an RTL version of it. Currently, we don't have this on our roadmap. 
If you create one we'll be happy to mention it on our landing page for this template.

**Comment by kossa** [comment]
I did not found a RTL for bootstrap 4 right now, I'll check again ;)

**Comment by AndreiCN** [comment]
Hi there @kossa, if you decide to make a RTL version of it please create a PR in order to improve the template. We will close this ticket for now, regards !

**Comment by kossa** [comment]
Oh thank you

**Comment by webineh** [comment]
this bootstrap 4 work fine . 

http://rtlcss.com/cdn/css-frameworks/bootstrap/

but you need add 
``dir = "rtl"``
in html

<html dir="rtl">
