### ISSUE TITLE
I need just light build version of the Menu

### ISSUE THREAD

**Issue by ahmadsamei** [puikinsh/Adminator-admin-dashboard#264]
Hi
I need just the menu of this project.
I want use just js and css files that need for menu, so I need a light version. But I couldn't compile and seperate the menu details from all file.

Please help me, that would be awesome and would save lots of people lots of time.

Thank you from the bottom of my heart ❤️

**Comment by jepperaskdk** [comment]
Hi, thanks for posting. I don't think it will be a goal of this theme to provide a menu-only version. The easiest is probably to strip out all the parts that you don't need.
