### ISSUE TITLE
Uncaught TypeError: can't access property "__k", u is null

### ISSUE THREAD

**Issue by rahatur** [puikinsh/Adminator-admin-dashboard#277]
### Bug Report

# Current behavior
js error in browser console which says "Uncaught TypeError: can't access property "__k", u is null"

# Expected behavior 
No js error in browser

# Environment
Platform: Windows 10
Browser: Google Chrome and Firefox (latest version)

For building issues:
Node: v14.16.0
NPM: 6.14.11

**Browser Log:**
Uncaught TypeError: can't access property "__k", u is null
    N https://colorlib.com/polygon/adminator/main.js:7592
    handleRenderRequest https://colorlib.com/polygon/adminator/main.js:1153
    node_modules fullcalendar/common/main.js/DelayedRunner.prototype.drained@https://colorlib.com/polygon/adminator/main.js:882
    node_modules fullcalendar/common/main.js/DelayedRunner.prototype.tryDrain@https://colorlib.com/polygon/adminator/main.js:881
    node_modules fullcalendar/common/main.js/DelayedRunner.prototype.request@https://colorlib.com/polygon/adminator/main.js:876
    node_modules fullcalendar/core/main.js/Calendar.prototype.render@https://colorlib.com/polygon/adminator/main.js:1158
    js https://colorlib.com/polygon/adminator/main.js:1801
    js https://colorlib.com/polygon/adminator/main.js:1801
    __webpack_require__ https://colorlib.com/polygon/adminator/main.js:7799
    fn https://colorlib.com/polygon/adminator/main.js:7811
    js https://colorlib.com/polygon/adminator/main.js:1805
    __webpack_require__ https://colorlib.com/polygon/adminator/main.js:7799
    <anonymous> https://colorlib.com/polygon/adminator/main.js:7880
    <anonymous> https://colorlib.com/polygon/adminator/main.js:7880
main.js:7592:8772

**Comment by jepperaskdk** [comment]
Fixed in https://github.com/puikinsh/Adminator-admin-dashboard/pull/286 - thanks for submitting this!
