### ISSUE TITLE
Can you release the static HTML version of this template?

### ISSUE THREAD

**Issue by MrClan** [puikinsh/Adminator-admin-dashboard#28]
With node-independent static HTML version, the template can be integrated into any server side technologies, and would also make this template usable in much more wider scenarios and with much ease.
Thanks.

**Comment by puikinsh** [comment]
Just compile it and you will get a plain HTML version of it. It doesn't require Node or anything else to run once compiled. It is just an HTML template.

**Comment by clain4u** [comment]
The template is totally useless for anyone who does not know node, If its an HTML template why don't you release it as HTML? 

Had trouble building it, ok after building it there was the vendor.js and bundle.js come on which has everything superimposed to one script file.

There is no scope of customization, its not al all ready to use, one have to invest a lot of time to get this working the way they wanted it.

Technology is good, but this is an overkill.
