### ISSUE TITLE
Not able to plugin to Yii2 Framworks

### ISSUE THREAD

**Issue by lvsan** [puikinsh/Adminator-admin-dashboard#288]
Hi,

May i know does this able to be use under Yii2 framework PHP and mySQL.
If yes, can advise me how can i plugin it under yii2? I have try but not working.

Thanks.

Regards.
lvsan

**Comment by jepperaskdk** [comment]
What have you tried? What isn't working?
You will need to break down the layout into components that you use in your target framework.

**Comment by jepperaskdk** [comment]
Closing due to no response.
