### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by jepperaskdk** [puikinsh/Adminator-admin-dashboard#289]
Hey @puikinsh,

I love this theme and use it a lot. Is this project still being maintained or what's the status?
Last commit is from Jun 29, 2021. I'm more than happy to help with the continued development of the theme.

**Comment by puikinsh** [comment]
Hey @jepperaskdk 

We haven't discontinued this template and it is currently in maintenance mode. We'll update it to the latest version of Bootstrap and do other improvements to keep it up-to-date. 

However, let me know how you see the growth and development of this template.

**Comment by jepperaskdk** [comment]
Awesome. 

There are some questions related to prebuilding the static CSS/JS. I suppose that could be possible by setting up a release pipeline, that automatically creates the release and attaches the built theme.

Building is no problem at least: https://github.com/jepperaskdk/Adminator-admin-dashboard/runs/7783850396?check_suite_focus=true


And we should try to review the pull-requests.

**Comment by puikinsh** [comment]
@jepperaskdk I have added you as a contributor to this repo. 

Great idea with a change in the setup! You can go ahead and implement it.
