### ISSUE TITLE
Why does it need Python?

### ISSUE THREAD

**Issue by benisai** [puikinsh/Adminator-admin-dashboard#296]
Why does it need Python? The read.me doesnt show it as required.

npm ERR! gyp verb check python checking for Python executable "python2" in the PATH

**Comment by GhostHyde** [comment]
Ran into as well with an NPM Pyton2 syntax error.  Had to abort installation.

**Comment by jepperaskdk** [comment]
It looks like it might be a dependency of `node-sass` - I think this PR will solve it: https://github.com/puikinsh/Adminator-admin-dashboard/pull/294

**Comment by jepperaskdk** [comment]
I've merged that PR now - can you pull the latest and check if it works now?
