### ISSUE TITLE
Need HTML version

### ISSUE THREAD

**Issue by dgrvedado** [puikinsh/Adminator-admin-dashboard#298]
Hi!!

I need the version complete in html. is so possible use this panel without npm command? I need open index.html and see the complete site with out npm run dev...

Thank!!!,
David

**Comment by jepperaskdk** [comment]
Hey, you can find the precompiled files both minified and unminified under each release:
https://github.com/puikinsh/Adminator-admin-dashboard/releases/tag/v2.0.4
