### ISSUE TITLE
WHAT is the license for use?

### ISSUE THREAD

**Issue by freesoftwarewiz** [puikinsh/Adminator-admin-dashboard#3]
Is this licensed under MIT or what?

Thanks
Joe C
Cheif Engineer

**Comment by puikinsh** [comment]
MIT

**Comment by freesoftwarewiz** [comment]
Thank you. One other quick question: I could not find an actual working demo of this - is there one, and if so, could you provide a link?

**Comment by puikinsh** [comment]
Not yet but you can easily launch preview locally by following instructions steps in the Readme.

**Comment by freesoftwarewiz** [comment]
We are in middle of the thanksgiving holiday here, so Im not sure I’ll have time immediately. It is. Nice lokking template.

If the sidebar menus get long vertically, does the sidebar scroll (independant of display area)

And is it possible to insert an image in the sidebar without it screwing up how sidebar functions? :-)
