### ISSUE TITLE
Setup main.js for project

### ISSUE THREAD

**Issue by coosta09** [puikinsh/Adminator-admin-dashboard#300]
<h1>Support request</h1>
I can't get the application running as-is. It complains about a main.js when I call 'npm run dev' and I have no idea what should be in the file.

# Current behavior

When I call npm run dev in my terminal, it says main.js is a problem.

# Expected behavior 

Application should get started

# Environment
Platform: Mac terminal
Browser: 

For building issues:
Node:  v20.10.0         
NPM:  v10.2.3

**Comment by jepperaskdk** [comment]
Can you add a full stacktrace?

**Comment by coosta09** [comment]
Sorry, project is actually running, I couldn't see the full logs in my terminal. Thanks
