### ISSUE TITLE
New html page has no styling

### ISSUE THREAD

**Issue by coosta09** [puikinsh/Adminator-admin-dashboard#301]
<h1>Support request</h1>

I'm trying to create a new page but when it opens it doesn't have the correct styling.

# Current behavior

I copied the blank.html file and pasted it in the 'src' folder with a different name. The rest of the site still has styling but when I navigate to my new page it has no styling.

# Expected behavior 

The new page should have the same style/theme as the rest of the project

# Environment
Platform: Mac
Browser: Safari

For building issues:
Node: 20.10.0   
NPM: 10.2.3

**Comment by jepperaskdk** [comment]
Perhaps it needs to be added to this file: webpack/plugins/htmlPlugin.js
Can you test it out?

**Comment by coosta09** [comment]
@jepperaskdk thanks a lot. That sorted it out
