### ISSUE TITLE
Change background colour

### ISSUE THREAD

**Issue by coosta09** [puikinsh/Adminator-admin-dashboard#302]
<h1>Documentation issue</h1>

# Current behavior

I'm trying to change the background colour of the main canvas. Seems like a simple question but I haven't been able to figure it out. When I have this `<body style='background-colour:red'>`, the frame of the page is only red for a second as the body loads.

# Expected behavior 

I'd expect the background colour of the main area to change to red.

# Environment
Platform: Mac
Browser: Safari

For building issues:
Node:     20.10.0 
NPM:      10.2.3

**Comment by jepperaskdk** [comment]
Can you elaborate exactly what you are trying to change the color of? "main canvas"?

If you mean the red part here:
![image](https://github.com/puikinsh/Adminator-admin-dashboard/assets/10128260/93563390-eab8-4df4-8faa-9017ef9e61ff)

Then that is controlled by the `<main>` element, so remove "bgc-grey-100" and set something else.
```
<main class='main-content bgc-grey-100'>
```
