### ISSUE TITLE
Get this errors with laravel

### ISSUE THREAD

**Issue by jokarvu** [puikinsh/Adminator-admin-dashboard#32]
![deepinscreenshot_select-area_20180116112841](https://user-images.githubusercontent.com/31339414/34986714-82263fe2-fab0-11e7-9c8a-6e7e71d5b347.png)
How can i fix it? pls

**Comment by haliliceylan** [comment]
how did you install adminator on laravel ? Can you give me tutorial video for about that ?
I tried but i couldn't

**Comment by jokarvu** [comment]
1. Copy src/assets to resources/assets (laravel)
2. Merge dependences in packages.json
3. Edit webpack.mix.js (laravel)
4. npm run dev
But some javascript feature doesnt work correctly and i'm trying to fix it

**Comment by haliliceylan** [comment]
I will try. thanks

**Comment by jokarvu** [comment]
1. Copy src/assets to resources/assets (laravel)
2. Merge dependences in packages.json then update npm with command: npm update
3. Edit webpack.mix.js (laravel)
4. npm run dev
But some javascript features did not work correctly and i'm trying to fix it

**Comment by krzysiekpiasecki** [comment]
In general you must generate a manifest.json file using web pack plugin which contains a map of files and hashes. Then, in templating system, call a function which dynamically map asset name into a hash name. 

Maybe this project will help you resolve your problem https://github.com/krzysiekpiasecki/Symfonator.

**Comment by krzysiekpiasecki** [comment]
Here is even  Laravel implementation https://github.com/kossa/laradminator

**Comment by aslamrahman** [comment]
Hi @jokarvu, can you share your webpack.mix.js (laravel).

**Comment by jokarvu** [comment]
`let mix = require('laravel-mix');
mix.js('resources/assets/scripts/index.js', 'public/js')
   .sass('resources/assets/styles/index.scss', 'public/css');`
@aslamrahman

**Comment by jokarvu** [comment]
`https://github.com/kossa/laradminator.git` May this project help you. Thank to Krzysztof Piasecki

**Comment by jokarvu** [comment]
Solved by using `webpack.min.js` and `package.json` of https://github.com/kossa/laradminator.gitom/kossa/laradminator.git`
