### ISSUE TITLE
How do i implementing it to codeigniter?

### ISSUE THREAD

**Issue by lramadhan** [puikinsh/Adminator-admin-dashboard#34]
I was installing it, and i could run it well.
Actually i'm new to programming, and not familiar with your technology.

and my question is `How do i implementing it to codeigniter?`, since this is not a conventional technology, i didn't even understand where is the assets that i could apply to codeigniter.

This is not an issue, but i only wanna ask it, thanks for your great project!

**Comment by AndreiCN** [comment]
Since this is a front-end template we haven't test it with CodeIgniter but [this](https://codeigniter.com/) could help you :)

Also if you don't have further questions please close the ticket, regards !
