### ISSUE TITLE
Suspension of npm run build

### ISSUE THREAD

**Issue by krzysiekpiasecki** [puikinsh/Adminator-admin-dashboard#38]
After cloning this repository then `npm run build` process hang at:

Child extract-text-webpack-plugin ../../node_modules/extract-text-webpack-plugin/dist ../../node_modules/css-loader/index.js??ref--2-1!../../node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css:
       2 modules

**Comment by 4mon** [comment]
me too!

**Comment by alkar1** [comment]
and me too !

**Comment by nandeeshmp** [comment]
Facing the same issue. Any fix/work around for this?

**Comment by AndreiCN** [comment]
Thank you guys for reporting this, we will solve it as soon as possible.

**Comment by AndreiCN** [comment]
It seems like I cannot reproduce it , I'm using v6.9.2 and it's working just fine. Can you please let me know what versions of node are you guys using?

**Comment by krzysiekpiasecki** [comment]
@AndreiCN 
| what versions of node are you guys using?

Reproduce using node:
         v6.0.0
        v6.11.5
         v8.0.0
         v8.1.4
         v8.8.1
         v8.9.1

So, definitely not related with node.

Console output:
![suspension](https://user-images.githubusercontent.com/4520629/35828279-34a901c2-0abf-11e8-82d7-0d6f7a70bb4e.png)


Updating modules - no positive.

**Comment by krzysiekpiasecki** [comment]
It's not a suspension. It's a socket connection open by the dashboard plugin which is also plugged in prod environment.

Removing this plugin from production configuration of webpack let the build process to exit successfully, so it's not a bug. Maybe the configs should be divided into a two separate files?

I think we can close this ticket.
