### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by ankitsoni18** [puikinsh/Adminator-admin-dashboard#39]
When i trying to intall npm on project it shows depricated files issues how i fix it to install theme correctly to use it ?
![image](https://user-images.githubusercontent.com/16620255/35268367-ea9559ca-004e-11e8-9b9a-7e330b36a8de.png)

**Comment by danielpettifer** [comment]
Which version of node are you using? I stopped getting deprecated file issues after running nvm use 8.5.0

**Comment by ankitsoni18** [comment]
@danielpettifer I'm using node 8.9

**Comment by danielpettifer** [comment]
I'm also having problems trying to get this running locally

**Comment by AndreiCN** [comment]
try to run it on a server and not locally and please share with us if it works properly, or if you solved this one after all, thank you ! "http://127.0.0.1:3000/index.html" - that's the server created by webpack.
