### ISSUE TITLE
Another install/build issue

### ISSUE THREAD

**Issue by walesdata** [puikinsh/Adminator-admin-dashboard#40]
Hello!

I am using node version 4.8.7, and NPM version 2.15.11. I am on Linux Mint, read by the installer as Linux 4.13.0-26-generic. I have been following the instructions in the readme file. I got through the npm install step after installing a bunch of packages. When I went to the NPM build part, I get this error:

> adminator@1.0.0 build /home/jwales/UnzipLand/dashboard/adminator
> npm run clean && cross-env NODE_ENV="production" webpack

> adminator@1.0.0 clean /home/jwales/UnzipLand/dashboard/adminator
> shx rm -rf ./build

/home/jwales/UnzipLand/dashboard/adminator/webpack/rules/css.js:27
let rule = {};
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jwales/UnzipLand/dashboard/adminator/webpack/rules/index.js:4:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 4.13.0-26-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! adminator@1.0.0 build: `npm run clean && cross-env NODE_ENV="production" webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adminator@1.0.0 build script 'npm run clean && cross-env NODE_ENV="production" webpack'.
npm ERR! This is most likely a problem with the adminator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && cross-env NODE_ENV="production" webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs adminator
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls adminator
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jwales/UnzipLand/dashboard/adminator/npm-debug.log

I have also attached the recommended file.
[npm-debug.log](https://github.com/puikinsh/Adminator-admin-dashboard/files/1661819/npm-debug.log)

Any help would be much appreciated. Thank you!

**Comment by jepperaskdk** [comment]
Try upgrading your node-version, that fixed it for me.

**Comment by AndreiCN** [comment]
Hi @walesdata, please let us know if by updating to the latest version of node the problem get solved, thank you !

**Comment by krzysiekpiasecki** [comment]
@AndreiCN @walesdata 

I reproduced it until node@8.0.0. The problem is also with ```npm run dev```.

**Comment by goodhands** [comment]
I am having a quite similar issue. I have node v8.9.4.
The errors below show up when I ran npm install

npm ERR! path C:\xampp\htdocs\adminator\node_modules\acorn\bin\acorn
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\xampp\htdocs\admina
tor\node_modules\acorn\bin\acorn'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Olaegbe Samuel\AppData\Roaming\npm-cache\_logs\2018-02-19T
02_45_30_073Z-debug.log

**Comment by msaus** [comment]
I am getting the same issue.
Have you found the solution?
I am trying different version of nodejs but it dose not work.

**Comment by msaus** [comment]
I tried following commands and I got another errors..
```
sudo apt-get purge nodejs* 
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash - 
sudo apt-get install -y nodejs
sudo npm install -g npm
```
```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! adminator@1.0.0 build: `npm run clean && cross-env NODE_ENV="production" webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the adminator@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-02-23T04_59_57_688Z-debug.log

```

This is log file that is given.
```
0 info it worked if it ends with ok                                                                                                                                                     
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v9.6.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle adminator@1.0.0~prebuild: adminator@1.0.0
6 info lifecycle adminator@1.0.0~build: adminator@1.0.0
7 verbose lifecycle adminator@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle adminator@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vagrant/offshore/adminator/node_modules/.bin:/home/vagrant/bin:/home/vagrant/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle adminator@1.0.0~build: CWD: /home/vagrant/offshore/adminator
10 silly lifecycle adminator@1.0.0~build: Args: [ '-c',
10 silly lifecycle   'npm run clean && cross-env NODE_ENV="production" webpack' ]
11 silly lifecycle adminator@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle adminator@1.0.0~build: Failed to exec build script
13 verbose stack Error: adminator@1.0.0 build: `npm run clean && cross-env NODE_ENV="production" webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:127:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:127:13)
13 verbose stack     at maybeClose (internal/child_process.js:933:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid adminator@1.0.0
15 verbose cwd /home/vagrant/adminator
16 verbose Linux 4.4.0-81-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v9.6.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error adminator@1.0.0 build: `npm run clean && cross-env NODE_ENV="production" webpack`
22 error Exit status 2
23 error Failed at the adminator@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
~                              
```

**Comment by krzysiekpiasecki** [comment]
Try to install node with (https://github.com/creationix/nvm). I have no problems with a build using branch 9.x. My npm version is 5.5.1. After installing run:

```
$ nvm install 9.0
$ nvm use 9.0
$ npm run build.
```


Follow also a thread https://github.com/webpack/webpack/issues/6323

**Comment by msaus** [comment]
thanks for your help.
I could install it.
