### ISSUE TITLE
Integration with final release of bootstrap 4

### ISSUE THREAD

**Issue by zerojuls** [puikinsh/Adminator-admin-dashboard#41]
Congratulations on this project, I would like to know if you have in your plans to update this project to the final release of bootstrap 4.

Thanks!

**Comment by puikinsh** [comment]
We'll update it eventually but since not many changes are required we'll appreciate if you could contribute to this update.

**Comment by krzysiekpiasecki** [comment]
@zerojuls May I ask you, to close this ticket?
