### ISSUE TITLE
Demo is not responsive

### ISSUE THREAD

**Issue by webchun** [puikinsh/Adminator-admin-dashboard#44]
Hi, nice work @puikinsh. Anyway the demo site https://colorlib.com/polygon/adminator/index.html seems doesn't work as expected (responsive) on mobile devices. Have you checked it?

**Comment by AndreiCN** [comment]
Hi there @webchun  can you please provide some screenshots with what doesn't work properly on mobile ? Thank you !

**Comment by webchun** [comment]
Sure, here they are
[
![eb2a04d7-80e2-45da-8590-1692206f1750](https://user-images.githubusercontent.com/4277547/35759134-588def92-08aa-11e8-9ca3-e2f13e5246f1.jpeg)
](url)
[
![09bb182f-f204-4c04-952c-ab3deda3b33d](https://user-images.githubusercontent.com/4277547/35759219-d950fa52-08aa-11e8-9ae0-65148dca85c3.jpeg)
](url)

**Comment by AndreiCN** [comment]
Ok, we will investigate this, thank you for reporting this !

**Comment by puikinsh** [comment]
The demo is not responsive because it doesn't run the latest version. The template itself is fully responsive. 
make sure to build it and test it yourself.

**Comment by rbrlortie** [comment]
Same issue here. You might want to update the demo because that's what projects managers are using to judge the platform's viability.

![image](https://user-images.githubusercontent.com/23345449/50110714-ebc41180-0208-11e9-9f02-b6156982e220.png)
