### ISSUE TITLE
Help Wanted: How to change datatables localization?

### ISSUE THREAD

**Issue by NikoGrano** [puikinsh/Adminator-admin-dashboard#45]
Hey, I have all in one js file. I want change datatables localization, how I can do it?

I get translation language from PHP, so I can only change var in the html.

**Comment by krzysiekpiasecki** [comment]
For example in a file src/assets/scripts/datatable/index.js inject french translation object:

```js
import * as $ from 'jquery';
import 'datatables';

export default (function () {
  $('#dataTable').DataTable( {
    language: {
        processing:     "Traitement en cours...",
        search:         "Rechercher&nbsp;:",
        lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
        info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
        infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
        infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
        infoPostFix:    "",
        loadingRecords: "Chargement en cours...",
        zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
        emptyTable:     "Aucune donnée disponible dans le tableau",
        paginate: {
            first:      "Premier",
            previous:   "Pr&eacute;c&eacute;dent",
            next:       "Suivant",
            last:       "Dernier"
        },
        aria: {
            sortAscending:  ": activer pour trier la colonne par ordre croissant",
            sortDescending: ": activer pour trier la colonne par ordre décroissant"
        }
    }
} );
}());
```

Read more on i18n of datatables here https://datatables.net/manual/i18n. If you haven't got any other question related to this issue, please close this ticket. Thanks.

**Comment by NikoGrano** [comment]
Thank you for telling where put this translation. I have never used node for managing js libraries so still learning.

However I get translation language from PHP. So I have this kind tag tag on HTML header:
```html
<head>
<script>
var contentLang = 'en';
</script>
</head>
```

So how I can tell datatables what translation must be used?

**Comment by krzysiekpiasecki** [comment]
```js
$('#example').DataTable( {
    language: {
        url: `/localisation/${contentLang}.json`
    }
} );
```

Just load translation file dynamically from cdn (use cdn URL) or from project resources (need to download). Available translation here https://datatables.net/plug-ins/i18n/.

**Comment by NikoGrano** [comment]
@krzysiekpiasecki 
Thank you! You made my day! I Would like buy cup of coffee for you, if I could.

Edit: Bought some coffee for you for 20PLN. Have a great day!
