### ISSUE TITLE
Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by kentastudillo** [puikinsh/Adminator-admin-dashboard#5]
Hi, tried running the app on my local machine and encountered the following error. 

<img width="825" alt="screen shot 2017-12-05 at 10 15 35 pm" src="https://user-images.githubusercontent.com/11402312/33611543-b54276a6-da09-11e7-9d15-d14d8c892c78.png">

**Comment by leonardok** [comment]
same here

**Comment by AndreiCN** [comment]
Not quite sure what happens there, if you follow the steps from readme file should get no error.

**Comment by jeffersonor900** [comment]
![sin titulo](https://user-images.githubusercontent.com/31443049/34057563-7974ccd4-e1a5-11e7-8734-cf0491858636.png)

**Comment by jeffersonor900** [comment]
when trying to follow the steps described, I do not load the css styles ... help pls

**Comment by kossa** [comment]
Very strange it works fine for me, please check the node/npm version (once updated rm node_modules and reinstall node packages)

For me : 
MacOs => 10.13
Node => v8.9.3
Npm => 5.6.0

The result of : npm run preview

![image](https://user-images.githubusercontent.com/1175584/34448994-b96fe2ca-ecf3-11e7-9b03-5de846a49600.png)

**Comment by AndreiCN** [comment]
After "npm run dev" , load it on the server created by webpack "http://localhost:3000/index.html" and will work for sure.
