### ISSUE TITLE
RTL version

### ISSUE THREAD

**Issue by smahi** [puikinsh/Adminator-admin-dashboard#54]
Hi,
I would like to make an RTL version, but I don't know where to start.
Please help.

**Comment by AndreiCN** [comment]
I suggest you to just take a RTL version of an existing template and look over it, certainly it's not easy. You  can take [this](https://www.w3.org/International/tutorials/bidi-xhtml/) as a starting guide.

**Comment by krzysiekpiasecki** [comment]
@smahi  Fork this repo and start the development process. When you're ready make a pull request. Probably  there are no plans for such a evelopment, where you could join to help.

| I would like to make an RTL version, but I don't know where to start.

There are many sources and tutorials:
https://www.w3.org/International/tutorials/bidi-xhtml/
https://rtl-css.net/tutorial/3-different-ways-rtl-your-css
https://medium.muz.li/web-design-for-right-to-left-languages-the-basics-287329d508cf

If you have no more questions, please close this ticket. Thanks.

**Comment by smahi** [comment]
@krzysiekpiasecki thank you so much.
