### ISSUE TITLE
Date Pickers example

### ISSUE THREAD

**Issue by anzolin** [puikinsh/Adminator-admin-dashboard#55]
Hi @puikinsh, how are you? Does the Adminator template have the **Date Picker component** support? I did not find an example like the [Gentelella](https://colorlib.com/polygon/gentelella/form_advanced.html) template. Hugs.

**Comment by krzysiekpiasecki** [comment]
Yes, it does.

Navigate:
https://colorlib.com/polygon/adminator/calendar.html

Then e.g click on 'All day event" - it should propagate a modal window, where you can find a date picker.

May I please you to close this ticket, If this is the answer for your question. Thanks.

**Comment by crazyfree** [comment]
Could you please provide time picker like `20:00` and/or `08:00 PM`. 
Much appreciated!
