### ISSUE TITLE
HTML5 and CSS template only

### ISSUE THREAD

**Issue by ibecir** [puikinsh/Adminator-admin-dashboard#58]
Hi,

I was trying to get only HTML and CSS from this template and I was unable to do it. 

Is there any way to extract only HTML and CSS and minimal JS if possible from this template. I don't want to have any dependencies to node and other technologies.

Thanks

**Comment by jepperaskdk** [comment]
You'll need Node to build the HTML/CSS/minimal JS, but once you have built the files, there are no dependencies on Node. Running the commands below should bundle the theme in a directory called "build", in which you find the files. Further development might be difficult without node/webpack however.
```
git clone https://github.com/puikinsh/Adminator-admin-dashboard.git
cd Adminator-admin-dashboard
npm install
npm run build
```
Doing this without node, would mean fetching the dependencies, transpiling, preprocessing, bundling and so on, by other means.

**Comment by krzysiekpiasecki** [comment]
@ibecir 

0. Install libraries with ```npm install```.
1. Take a blank.html file.
2. Install Sass preprocessor (https://sass-lang.com/install).
3. Go into src/assets/styles
4. Replace ```@import "~bootstrap/scss/bootstrap``` with ```@import "../../../node_modules/bootstrap/scss/bootstrap.scss``` in index.scss
5. Comment ```@import 'vendor/index'``` in the same file.
6. Run from ```src/assets/styles``` command ```sass index.scss stylesheet.css```
7. Copy processed file ```stylesheet.css``` into a directory with blank html.
8. Add in blank.html a tag in head section ```<link href="index.css" rel="stylesheet" type="text/css"/>```
9. Open blank.html.
...

You've got the HTML template with CSS. After installing node modules copy required js libraries to folder with blank.html and add proper script tags. Generally speaking you must investigate in details, what you need, what you needn't.

Consider learning the whole ecosystem because it's a one of the standards for web applications and when you'll finish with this task - don't forget close it. Thanks.

**Comment by Yustyar** [comment]
@krzysiekpiasecki 
not 6 mean how ya i do not understand?

**Comment by krzysiekpiasecki** [comment]
> not 6 mean how ya i do not understand?

You need to transpile scss files into css.

**Comment by tecnoterabyte** [comment]
Work perfect @krzysiekpiasecki, what would be the best way to divide the stylesheet.css,

Regards,

**Comment by AndreiCN** [comment]
@ibecir if you have no further questions please close the ticket.

**Comment by clain4u** [comment]
> @ibecir
> 
>     1. Install libraries with `npm install`.
> 
>     2. Take a blank.html file.
> 
>     3. Install Sass preprocessor (https://sass-lang.com/install).
> 
>     4. Go into src/assets/styles
> 
>     5. Replace `@import "~bootstrap/scss/bootstrap` with `@import "../../../node_modules/bootstrap/scss/bootstrap.scss` in index.scss
> 
>     6. Comment `@import 'vendor/index'` in the same file.
> 
>     7. Run from `src/assets/styles` command `sass index.scss stylesheet.css`
> 
>     8. Copy processed file `stylesheet.css` into a directory with blank html.
> 
>     9. Add in blank.html a tag in head section `<link href="index.css" rel="stylesheet" type="text/css"/>`
> 
>     10. Open blank.html.
>         ...
> 
> 
> You've got the HTML template with CSS. After installing node modules copy required js libraries to folder with blank.html and add proper script tags. Generally speaking you must investigate in details, what you need, what you needn't.
> 
> Consider learning the whole ecosystem because it's a one of the standards for web applications and when you'll finish with this task - don't forget close it. Thanks.

Simply not ready to give a pure build versions , we understand , thanks you..!!

**Comment by trinanda** [comment]
> > @ibecir
> > ```
> > 1. Install libraries with `npm install`.
> > 
> > 2. Take a blank.html file.
> > 
> > 3. Install Sass preprocessor (https://sass-lang.com/install).
> > 
> > 4. Go into src/assets/styles
> > 
> > 5. Replace `@import "~bootstrap/scss/bootstrap` with `@import "../../../node_modules/bootstrap/scss/bootstrap.scss` in index.scss
> > 
> > 6. Comment `@import 'vendor/index'` in the same file.
> > 
> > 7. Run from `src/assets/styles` command `sass index.scss stylesheet.css`
> > 
> > 8. Copy processed file `stylesheet.css` into a directory with blank html.
> > 
> > 9. Add in blank.html a tag in head section `<link href="index.css" rel="stylesheet" type="text/css"/>`
> > 
> > 10. Open blank.html.
> >     ...
> > ```
> > 
> > 
> > You've got the HTML template with CSS. After installing node modules copy required js libraries to folder with blank.html and add proper script tags. Generally speaking you must investigate in details, what you need, what you needn't.
> > Consider learning the whole ecosystem because it's a one of the standards for web applications and when you'll finish with this task - don't forget close it. Thanks.
> 
> Simply not ready to give a pure build versions , we understand , thanks you..!!

This not works for me

**Comment by trinanda** [comment]
> > @ibecir
> > ```
> > 1. Install libraries with `npm install`.
> > 
> > 2. Take a blank.html file.
> > 
> > 3. Install Sass preprocessor (https://sass-lang.com/install).
> > 
> > 4. Go into src/assets/styles
> > 
> > 5. Replace `@import "~bootstrap/scss/bootstrap` with `@import "../../../node_modules/bootstrap/scss/bootstrap.scss` in index.scss
> > 
> > 6. Comment `@import 'vendor/index'` in the same file.
> > 
> > 7. Run from `src/assets/styles` command `sass index.scss stylesheet.css`
> > 
> > 8. Copy processed file `stylesheet.css` into a directory with blank html.
> > 
> > 9. Add in blank.html a tag in head section `<link href="index.css" rel="stylesheet" type="text/css"/>`
> > 
> > 10. Open blank.html.
> >     ...
> > ```
> > 
> > 
> > You've got the HTML template with CSS. After installing node modules copy required js libraries to folder with blank.html and add proper script tags. Generally speaking you must investigate in details, what you need, what you needn't.
> > Consider learning the whole ecosystem because it's a one of the standards for web applications and when you'll finish with this task - don't forget close it. Thanks.
> 
> Simply not ready to give a pure build versions , we understand , thanks you..!!

This not work for me,
can you provide the file in your repository, please..?

**Comment by trinanda** [comment]
> You'll need Node to build the HTML/CSS/minimal JS, but once you have built the files, there are no dependencies on Node. Running the commands below should bundle the theme in a directory called "build", in which you find the files. Further development might be difficult without node/webpack however.
> 
> ```
> git clone https://github.com/puikinsh/Adminator-admin-dashboard.git
> cd Adminator-admin-dashboard
> npm install
> npm run build
> ```
> 
> Doing this without node, would mean fetching the dependencies, transpiling, preprocessing, bundling and so on, by other means.

This is what I want, thanks a lot Man :)

**Comment by sarowerj** [comment]
How can i write jquery in this project?
