### ISSUE TITLE
Laravel Implimentation

### ISSUE THREAD

**Issue by hafeez1042** [puikinsh/Adminator-admin-dashboard#60]
if anybody has issue on implementing Adminator with laravel, here is a repo for laravel implementation
[Adminator HTML5 Admin Template Laravel Implementation](https://github.com/hafeez1042/Adminator-HTML5-Admin-Template-Laravel-Implementation)

**Comment by krzysiekpiasecki** [comment]
Thanks for sharing us, but it's not an issue, so you can close this ticket, because it's not resolvable :) Ofcourse you can make a pull request to README file and put it there a link to your repository.
