### ISSUE TITLE
Menu switch glitch

### ISSUE THREAD

**Issue by ghost** [puikinsh/Adminator-admin-dashboard#61]
After you minimized-maximized menu, in full mode you got topbar Account dropdown cut off. I also tried full stock setup without changing anything in code - bug is still here. Also, you got blank page titled like "Chat", which is not critical but not correct too
![2](https://user-images.githubusercontent.com/31141913/36598337-d77bb484-18bc-11e8-85cd-696bb53fbcf3.png)
![default](https://user-images.githubusercontent.com/31141913/36598338-d79bcf76-18bc-11e8-993f-1f73e5815652.png)
P.S Sorry my English, as you can see it's not my language at all.

**Comment by krzysiekpiasecki** [comment]
> Also, you got blank page titled like "Chat", which is not critical but not correct too

@PavelLJ  Defects will be fixed after merging #63. So if you're sure that this pull request resolves the problems, please close this task. Thanks.

**Comment by krzysiekpiasecki** [comment]
@PavelLJ Fix was merged. Please close this ticket, if you have no more questions. Thanks.
