### ISSUE TITLE
[help] Where can I change font?

### ISSUE THREAD

**Issue by ghost** [puikinsh/Adminator-admin-dashboard#62]
Hello. I tried to change logo-text and $font-primary in scss, but nothing changed. I got .otf and .woff files with font, how can I change stock one to custom in my /assets/fonts/ folder? Tried @font-face, but it doesn't help.
P.S Font is Proxima Nova

**Comment by krzysiekpiasecki** [comment]
This should change the logo text without any problems.
```
<h5 class="lh-1 mB-0 logo-text">Adminator</h5>
```

In a file ```webpack/rules/fonts.js``` is the expression ```(eot|svg|ttf|woff|woff2)```. You must update this expression to bundle otf files too.


### Using import statement in scss file

At file src/assets/styles/spec/settings/fonts.scss add:
```
@import url('https://fonts.googleapis.com/css?family=Roboto');
$font-primary: 'Roboto'
```

**Comment by AndreiCN** [comment]
Since you got an answer for it we will close the ticket for now, good luck !
