### ISSUE TITLE
High CPU load in Firefox

### ISSUE THREAD

**Issue by vers-one** [puikinsh/Adminator-admin-dashboard#65]
Even a simple page like [UI elements](https://colorlib.com/polygon/adminator/ui.html) consumes about 6% of CPU in the latest version of Firefox. I suspect it is because of the invisible `div.spinner`. If you remove it using Developer Tools the CPU load drops to 0%.

**Comment by krzysiekpiasecki** [comment]
Reproduced. The benefits and measurments depends on the browsers.

**Comment by krzysiekpiasecki** [comment]
@vers-one Will be fixed with #66. May I ask you, if could check the benefits at http://adminator-bootstrap4-65.surge.sh/ui.html on Firefox?

**Comment by vers-one** [comment]
Wow, that was fast! Yes, http://adminator-bootstrap4-65.surge.sh/ui.html doesn't have this issue.

**Comment by krzysiekpiasecki** [comment]
So please, close the ticket, if you have no more questions. Thanks @vers-one.

**Comment by vers-one** [comment]
Thank you!
