### ISSUE TITLE
How to build with all unminified files and html comments in all html?

### ISSUE THREAD

**Issue by mmartain** [puikinsh/Adminator-admin-dashboard#67]
#I'm trying to find the command to build all the files so i don't need node anymore but cannot seem to find a good command to leave everything unminified and unbundled without it breaking all scripts/css.

Any possibility to explain how this could be done? Tnx

**Comment by krzysiekpiasecki** [comment]
See #58. Generally speaking you have to compile scss files to css, install js librararies with npm and modify html templates. 

This project uses webpack bundler so AFAIK there is no such a command.

**Comment by ronyyu** [comment]
Why do we have to build it?
Wouldn't it be easier to provide a pure html/js/css version for people who want to 'just' use it?
I lost 9 hours trying to build :(

**Comment by AndreiCN** [comment]
This is the way webpack works since this is a template build with it, ticket closed.
