### ISSUE TITLE
Dropdown menus render incorrectly in Edge 16

### ISSUE THREAD

**Issue by vers-one** [puikinsh/Adminator-admin-dashboard#68]
Steps to reproduce:
1. Open https://colorlib.com/polygon/adminator/ui.html in Edge.
2. Click on "Multiple Levels" menu arrow to expand it.
3. The following result appears:
![default](https://user-images.githubusercontent.com/12114169/36689994-ffd04f14-1afe-11e8-89ef-65436e9cd06b.png)

It is probably due to the `list-style-type: none` rendering bug in IE/Edge.

**Comment by AndreiCN** [comment]
Thank you for reporting this @vers-one.

**Comment by tecnoterabyte** [comment]
Word Perfect Edge.

Microsoft Edge 41.16299.248.0
Microsoft EdgeHTML 16.16299
Windows-10.

![yii2_dashboard_adminator_edge](https://user-images.githubusercontent.com/12988135/38120587-eacb90f4-3397-11e8-88cb-14b7a13b1548.png)

**Comment by DPTeamMember** [comment]
Hello @vers-one @tecnoterabyte 

We have resolved this issue in our latest release, The template is fully compatible with Edge, please check.

Thank you.

**Comment by vers-one** [comment]
Works properly in the latest (Chromium based) Edge. Thank you.
