### ISSUE TITLE
Uncaught error when display modal with bootstrap events

### ISSUE THREAD

**Issue by muhammad-ihsan** [puikinsh/Adminator-admin-dashboard#69]
![preview](https://image.prntscr.com/image/NvzC11nASD22Lbp55joZZg.png)

**Comment by krzysiekpiasecki** [comment]
@muhammad-ihsan May I please you, if you can provide us more details how to reproduce this error? Not only a screen shot.

Can you reproduce this defect here http://adminator-bootstrap4-65.surge.sh/ui.html

**Comment by muhammad-ihsan** [comment]
just write this `$('#exampleModal').modal('show');` in my console when trying to show the modal on these page [http://adminator-bootstrap4-65.surge.sh/ui.html](http://adminator-bootstrap4-65.surge.sh/ui.html). The modal wont show if we use the modal bootstrap javascript event.

**Comment by krzysiekpiasecki** [comment]
I've reproduced it also on a clean project, when the jquery and bootstrap scripts were loaded at incorrect order.

**Comment by muhammad-ihsan** [comment]
i've download the latest version today, but nothing change

**Comment by muhammad-ihsan** [comment]
no update? 😞

**Comment by muhammad-ihsan** [comment]
🥇

**Comment by arcticwalker** [comment]
Same here. $ does not have the bootstrap modal plugin loaded. It is hidden somewhere, I  had to add script tags to reload jQuery and bootstrap js again to expose the modal plugin.

**Comment by muhammad-ihsan** [comment]
Not updated yet? Still with the same error
![](https://image.prntscr.com/image/TPCt3FyoQhOfMRR2j8rqfw.png)

**Comment by ngoclanbaby86** [comment]
i'm waiting.... same issue

**Comment by AlexRToledo** [comment]
Hi I have the same issue, someone fixit?

**Comment by jonathanvgms** [comment]
Hi, i'm dealing with the same issue for weeks, the only workaround i can think off is use bootstrap's javascript and it works! but if i import the javascript doesn't work the option menu of user. :/

**Comment by jvilaplana** [comment]
Same issue here.

**Comment by r15h1** [comment]
@krzysiekpiasecki, do you have an update or workaround for this issue?

**Comment by hayodehaai** [comment]
Hello everyone,

I think I found the solution for this problem.

You should first import the jQuery library and the bootstrap's javascript, by adding the following lines of code between your `<head></head>` tags:

` <!-- jQuery library -->`
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>`

`<!-- Latest compiled JavaScript -->`
`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>`


I found out that the 'show' class issn't automatically add to the modal div when using

 `$('#exampleModal').modal('show');`

So, if you want to launch the modal from a script, you have to add a line of code to add the 'show' class to the modal div:

`$('#exampleModal').modal('show');`
**`document.getElementById("exampleModal").classList.add("show");`**

Remember to **remove** the show class when the modal hides (on button click), to keep the nice fade out animation. Do this by adding the following lines of code:

`    $('#exampleModal').on('hide.bs.modal', function (e) {
      document.getElementById("exampleModal").classList.remove("show");
    });`

I think this is a bug in adminator, but using this lines of codes solved the problem for me.

I hope you have been helped with this.

**Comment by sublimedatasys** [comment]
Answer=>Hi @muhammad-ihsan , @arcticwalker 

If you want to handle modal event via jquery then need to write there jquery function in the js file in assets/script where bootstrap and jquery is imported as

import * as $ from 'jquery';
import 'bootstrap';
And can perform both show and hide events without any error.
$('#myModal').modal('show')

$('#myModal').modal('hide')

Another way is to use a CDN link of Bootstrap and jquery in the HTML file.

Please note: That jquery should be imported before bootstrap. In this case the order of importing dependency is important.

Thank you
