### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by ronyyu** [puikinsh/Adminator-admin-dashboard#70]
ok, I followed the step provided here are errors I get (I'm not familiar with the nodejs environment)

> farmhash@1.2.1 install /home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/farmhash
> node-gyp rebuild

gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.4.0-51-generic
gyp ERR! command "/usr/bin/nodejs" "/home/rony/Documents/node-v9.7.1-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/farmhash
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> integer@1.0.3 install /home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/integer
> node tools/install

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/integer/build'
gyp ERR! System Linux 4.4.0-51-generic
gyp ERR! command "/usr/bin/nodejs" "/home/rony/Documents/node-v9.7.1-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/integer
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> gifsicle@3.0.4 postinstall /home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/gifsicle
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/gifsicle/vendor'
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
/home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/each-async/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at /home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:132:15)
    at finishMaybe (/home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/readable-stream/lib/_stream_writable.js:620:14)
    at endWritable (/home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/readable-stream/lib/_stream_writable.js:628:3)
    at ConcatStream.Writable.end (/home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/readable-stream/lib/_stream_writable.js:584:41)
    at DuplexWrapper.onend (/home/rony/Documents/node-v9.7.1-linux-x86/bin/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:219:13)
    at DuplexWrapper.emit (events.js:132:15)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: farmhash@1.2.1 (node_modules/farmhash):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: farmhash@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: integer@1.0.3 (node_modules/integer):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: integer@1.0.3 install: `node tools/install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gifsicle@3.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rony/.npm/_logs/2018-03-02T12_48_56_161Z-debug.log

**Comment by AndreiCN** [comment]
From what I see you're trying to build it using linux, since you're not quite familiar with node we suggest you to use a windows environment for instance, we will keep this open though maybe someone had the same issue considering that we didn't test it on linux.

**Comment by ronyyu** [comment]
Building on windows I had problems as well:
I downloaded the standalone version of node/npm

node-v8.9.4-win-x64> .\npm install
`PS C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64> .\npm install
npm WARN deprecated jvectormap@2.0.4: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\acorn -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\acorn\bin\acorn
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\ansi-html -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\ansi-html\bin\ansi-html
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\atob -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\atob\bin\atob.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\babylon -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\babylon\bin\babylon.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\blessed -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\blessed\bin\tput.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\color-support -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\color-support\bin.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\cssesc -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\cssesc\bin\cssesc
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\browserslist -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\browserslist\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\esvalidate -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\esprima\bin\esvalidate.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\esparse -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\esprima\bin\esparse.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\gonzales -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\gonzales-pe\bin\gonzales.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\he -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\he\bin\he
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\not-in-publish -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\in-publish\not-in-publish.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\in-publish -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\in-publish\in-publish.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\in-install -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\in-publish\in-install.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\not-in-install -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\in-publish\not-in-install.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\jsesc -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\jsesc\bin\jsesc
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\json5 -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\json5\lib\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\loose-envify -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\loose-envify\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\miller-rabin -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\miller-rabin\bin\miller-rabin
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\mime -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\mime\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\mkdirp -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\mkdirp\bin\cmd.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\nopt -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\nopt\bin\nopt.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\errno -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\errno\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\regjsparser -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\regjsparser\bin\parser
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\import-local-fixture -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\import-local\fixtures\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\rgb -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\rgb\bin\rgb
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\seek-table -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\seek-bzip\bin\seek-bzip-table
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\seek-bunzip -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\seek-bzip\bin\seek-bunzip
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\semver -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\semver\bin\semver
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\sha.js -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\sha.js\bin.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\specificity -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\specificity\bin\specificity
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\js-yaml -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\js-yaml\bin\js-yaml.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\strip-indent -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\strip-indent\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\rc -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\rc\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\csso -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\csso\bin\csso
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\strip-dirs -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\strip-dirs\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\multicast-dns -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\multicast-dns\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\sshpk-sign -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\sshpk\bin\sshpk-sign
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\sshpk-verify -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\sshpk\bin\sshpk-verify
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\sshpk-conv -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\sshpk\bin\sshpk-conv
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\uglifyjs -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\uglify-js\bin\uglifyjs
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\uuid -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\uuid\bin\uuid
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\executable -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\executable\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\find-versions -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\find-versions\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\bin-version-check -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\bin-version-check\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\internal-ip -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\internal-ip\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\lpad-align -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\lpad-align\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\svgo -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\svgo\bin\svgo
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\which -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\which\bin\which
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\handlebars -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\handlebars\bin\handlebars
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\inspectpack -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\inspectpack\bin\inspectpack.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\rimraf -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\rimraf\bin.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\shjs -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\shelljs\bin\shjs
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\html-minifier -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\html-minifier\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\har-validator -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\har-validator\bin\har-validator
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node-gyp -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\node-gyp\bin\node-gyp.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\sassgraph -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\sass-graph\bin\sassgraph
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\gifsicle -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\gifsicle\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\jpegtran -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\jpegtran-bin\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\optipng -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\optipng-bin\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\pngquant -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\pngquant-bin\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\cross-env -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\cross-env\dist\bin\cross-env.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\cross-env-shell -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\cross-env\dist\bin\cross-env-shell.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\eslint -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\eslint\bin\eslint.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node-sass -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\node-sass\bin\node-sass
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\shx -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\shx\lib\cli.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\stylelint -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\stylelint\bin\stylelint.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\webpack -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\webpack\bin\webpack.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\webpack-dashboard -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\webpack-dashboard\bin\webpack-dashboard.js
C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\webpack-dev-server -> C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\webpack-dev-server\bin\webpack-dev-server.js

> integer@1.0.3 install C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\integer
> node tools/install

'node' is not recognized as an internal or external command,
operable program or batch file.

> farmhash@1.2.1 install C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\farmhash
> node-gyp rebuild


C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\farmhash>if not defined npm_config_node_gyp (node "C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
'node' is not recognized as an internal or external command,
operable program or batch file.

> node-sass@4.7.2 install C:\Users\HP\Downloads\node-v8.9.4-win-x64\node-v8.9.4-win-x64\node_modules\node-sass
> node scripts/install.js

'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: integer@1.0.3 (node_modules\integer):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: integer@1.0.3 install: `node tools/install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: farmhash@1.2.1 (node_modules\farmhash):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: farmhash@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2018-03-03T04_06_09_103Z-debug.log`



:/

**Comment by 34r7h** [comment]
Seems related on OSX
```
io:itsli7.com i$ sudo npm install rabin --save

> rabin@1.6.0 install /Users/i/Apps/itsli7.com/node_modules/rabin
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.11.3 runtime=node arch=x64 platform=darwin)
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir'/Users/i/Apps/itsli7.com/node_modules/rabin/build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/i/Apps/itsli7.com/node_modules/rabin
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN The package express is included as both a devand production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rabin@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rabin@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/i/.npm/_logs/2018-11-27T21_04_15_261Z-debug.log

**Comment by krzysiekpiasecki** [comment]
@ronyyu @34r7h please provide versions of npm and node.

**Comment by krzysiekpiasecki** [comment]
Closed due to inactivity. Source of this issue - incompatibility npm - node?
