### ISSUE TITLE
Is there an already built version of it?

### ISSUE THREAD

**Issue by ronyyu** [puikinsh/Adminator-admin-dashboard#71]
HI where can I find a built version of this template?
I would like to use it in a java/spring project

So I just need the  html / js / css part where I can modify on my own without getting into the node environment. I don't want to do big changes !

If someone can build it and put it somewhere as a zip, that would be great.

**Comment by AndreiCN** [comment]
Duplicate of #67 , if you have no further questions please close the ticket.

**Comment by sandervandegeijn** [comment]
I'm sorry but I tend to agree, it looks really nice, just tried to build it on Linux and I'm running into multiple dependencies that need to be installed in order to build.

Installed: shx, cross-env

```
> shx rm -rf ./build

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
    at onErrorNT (internal/child_process.js:363:16)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickCallback (node.js:425:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:140:18)
    at node.js:1043:3

```

Not really user friendly :) Pre-compiled versions published to a repo by a build engine would be a lot nicer, or just a docker container that's ready to go if you really don't want to setup a build pipeline.

**Comment by ronyyu** [comment]
@AndreiCN I know it's a duplicate, but we were at least 3 persons asking without getting a built version. It's kind of frustrating. When we download ad open source software, we can download the source and build it, or download binaries and execute it without building. When I download Tomcat, they don't force me to have the JDK on my machine for example.

What is the reason here? are you still in development and want to have a "final" version before release it as a built version?
In that case I can agree and wait, but I don't see any explanation on this.

**Comment by AndreiCN** [comment]
Well it depends on which environment you're builing it, on Windows for instance with a proper usage you will get no errors. Nevertheless, we will work on a solution for this , thank you !

**Comment by sandervandegeijn** [comment]
Cool, this would be nice! I really like the template :)

*puppy eyes: could you package up the current release and drop it somewhere as a zip/tar/whatever? I'm currently working on a project and I would like to use the template, but my build is failing as you can see :)

Thanks!

**Comment by mtik00** [comment]
Not sure how useful this is to you, but here you go.  This was built from a just-cloned repo using `npm run build` on Windows.
[build.zip](https://github.com/puikinsh/Adminator-admin-dashboard/files/1778711/build.zip)

**Comment by sandervandegeijn** [comment]
Very useful, great, thanks a lot!

Integrating it in my project now :)

**Comment by ronyyu** [comment]
Thank you very much! I really appreciate this :)

**Comment by hmdnprks** [comment]
Finally someone upload it
Very useful . Thank you @mtik00

**Comment by jaequery** [comment]
Problem is that entire javascript is minified in to the bundle and vendor.js. Is there anyway we can have that separated out so we have control over it?

**Comment by titus-j** [comment]
I'd also like to use it with Java/Spring. So +1 for a version that supports that better

**Comment by damms005** [comment]
+1 for "normal" template in which exports and imports and splicing and buildings and compilings and npm-ing are all not needed. All files remaining in their normal, ordinary form - bootstrap stays in its normal folder...etc. This is awesome library that deserves universal usage and not restricted to persons that can do the above.

**Comment by corwincooper** [comment]
+1. I'd like to use this with Java/Play Framework. I managed to build the templeate however, but it's a bit tricky, imho. I have to install a lot of dependencies, build the template, and decompress the output since I need plain-old html/css to program my app's templates using its templates engine.

**Comment by arriagadadev** [comment]
In [this repository](https://github.com/arriagadadev/Adminator-admin-dashboard-laravel) you can see this template in a laravel 6.x (blade) adaptation too.
In the "public" folder you can get the javascript and css files not minified too.

**Comment by idpdka** [comment]
Thank you bro @arriagadadev you saved my a$$

**Comment by idpdka** [comment]
Thank you bro @arriagadadev just in time I want to build laravel version of this

**Comment by arriagadadev** [comment]
It's a pleasure, @idpdka 
remember to update laravel to version 7.x!

**Comment by dinis-rodrigues** [comment]
> Problem is that entire javascript is minified in to the bundle and vendor.js. Is there anyway we can have that separated out so we have control over it?

In this case I just use the Prettier extension/formatter in vs code, it de-minifies all the code!

**Comment by jepperaskdk** [comment]
From 2.0.3 we prebuild both minified and unminified static assets for each release: https://github.com/puikinsh/Adminator-admin-dashboard/releases

You can build these yourself as well, using `npm run release:unminified` or `npm run release:minified`.
