### ISSUE TITLE
.css and .js in webroot

### ISSUE THREAD

**Issue by sandervandegeijn** [puikinsh/Adminator-admin-dashboard#72]
bundle.js
vendor.js
style.css 

are now in the root folder. Shouldn't they be in the assets folder?

**Comment by krzysiekpiasecki** [comment]
@neographikal I don't think it's a ```must have``` feature, and even ```should have``` feature at the moment, but If you think it's right please make a pull request. May I please you to close this ticket, because there is no discussion, and this post is actually a request for comment.
