### ISSUE TITLE
Ajax call for php pages

### ISSUE THREAD

**Issue by Radnik** [puikinsh/Adminator-admin-dashboard#74]
Hi devs,
Sorry if I am missing something...but
Where and how can one add support for ajax calls for PHP pages?.

Here is really simple code:

index.html
```
<script type="text/javascript">
      $(document).ready(function(){
        $.ajax(
          {
            url: 'test.php',
            type: 'get',
            dataType:'text',
            success: function(data){
                console.log(data);
            }
          });
      });
    </script>
```

test.php
```
<?php
   echo "1";
   echo "2";
   echo "3";
   echo "4";
   echo "5";
   echo "6";
   echo "7";
   echo "8";
?>
```

The result in the console is:
```
[HMR] Waiting for update signal from WDS...
[Violation] Forced reflow while executing JavaScript took 137ms 
<?php
   echo "1";
   echo "2";
   echo "3";
   echo "4";
   echo "5";
   echo "6";
   echo "7";
   echo "8";
?>
[WDS] Hot Module Replacement enabled.
[Violation] 'setTimeout' handler took 105ms
```

Many Thanks!

**Comment by ronyyu** [comment]
HI,

this is more a php related question. So it's not the good place to ask. It's better to ask this on stackoverflow.

But according to what I see, it seems like the php code is not interpreted and the ajax call returns the php file content instead of returning a result. Do you have a php server running?

if you go to http://localhost/test.php (assuming that your are running on localhost) what do you get?

**Comment by Radnik** [comment]
Hey ronyyu,

Running HHVM with root folder `/opt/home/`.
All .php files shows fine there, e.g. http://localhost/test.php -> OK

On the other hand, inside `/opt/home/adminator/ ` where adminator has been git cloned none of the .php files are parsed. 

Using `npm build dev` (port 3000) all .php files get downloaded and same is with regular `npm run build`

http://localhost:3000/test.php -> Get downloaded like file
http://localhost/adminator/build/test.php -> Get downloaded like file

THX

**Comment by ronyyu** [comment]
I don't know how HHVM works. Are you using a reverse proxy?
Maybe you have to configure the adminator folder somewhere.

Also check this answer may help https://stackoverflow.com/questions/29541378/nginx-downloads-php-files-instead-of-executing-them-hhvm

**Comment by AndreiCN** [comment]
This is a HTML so front-end template. If you have a question related to that we will be more than happy to hear it, if you don't please close the ticket.
