### ISSUE TITLE
When loading dataTable with ngView, show and search box doesn't loads

### ISSUE THREAD

**Issue by harishnagi008** [puikinsh/Adminator-admin-dashboard#77]
Hi,
This is my first ever issue on github.

When I am loading the `dataTable `from the adminator theme using the `ngView `of `AngularJS `in my project, `show `and `search `box is missing, also I am not able to `sort `the table on click of columns.

Here's the code snippet of the `index.html`
```
<main class="main-content bgc-grey-100">
            <div ng-view id="mainContent" >

            </div>      
        </main> <!-- main ends -->
```
dataTable code comes from another file called `user.html.`

`<div class="container-fluid">`
            `<h4 class="c-grey-900 mT-10 mB-30">Data Tables</h4>`
            `<div class="row">`
              `<div class="col-md-12">`
                `<div class="bgc-white bd bdrs-3 p-20 mB-20">`
                  `<h4 class="c-grey-900 mB-20">Bootstrap Data Table</h4>`
`..........<!---and so on-->`

This file is loaded as partial template into `index.html` using `ngView`.

This is how it should look.
![main](https://user-images.githubusercontent.com/33452127/37728270-cefba474-2d5f-11e8-9ef5-2d93228beb93.png)

This is how it looks without those options.
![main2](https://user-images.githubusercontent.com/33452127/37728189-a4a9dbaa-2d5f-11e8-927f-032ea4bc9304.png)

I am not understanding why this is happening. Please help me out in resolving this issue.

**Comment by krzysiekpiasecki** [comment]
@harishnagi008 Please provide more input:
- Browser name,
- Any console output?
- Exists the missing elements in the DOM?
- Which version of datatable and jquery ```npm list --depth=0``` 
- How do you create datable instance - custom options?  (code)
- Maybe you could share us your code.

**Comment by krzysiekpiasecki** [comment]
@harishnagi008 Still got a problem?

**Comment by canaria10** [comment]
Yes, this issue is still exists. I am now currently experiencing this.
