### ISSUE TITLE
Integrate into web application, no CSS reference in html file

### ISSUE THREAD

**Issue by cyberfly** [puikinsh/Adminator-admin-dashboard#78]
Hi guys I want to integrate this admin template into Laravel framework, however when I open the html file inside src folder, there is no reference to any CSS file. How can I properly reference the CSS file when integrate with PHP framework?

Thanks

**Comment by krzysiekpiasecki** [comment]
@cyberfly  Generally speaking, you must integrate a build result, which is placed in a ```dist``` directory, not ```src```.

Here you have the examples of incorporating this template into a two PHP frameworks:
https://github.com/kossa/laradminator
https://github.com/krzysiekpiasecki/Symfonator

Good luck and please close this ticket, if you don't have any further questions.

**Comment by pagra93** [comment]
Hello, is there any tutorial where explain how can I integrate this theme to my webpage or a guide, because I am a beginner in this things but I am interested to improve and I would like to know how I can do it. THANKS YOU

**Comment by DuudeXX8** [comment]
pagra93  he is right .

First. I can't find **dist** directory :(
Second. This styles don't work
Third.I'm not a backend developer I don't realize how to install this admin panel .
Fourth. I did everything all that wrote in bottom

 ```
git clone https://github.com/puikinsh/Adminator-admin-dashboard.git adminator
> cd adminator
> npm install
> npm run dev
```

and what i got? the file without styles :( 

and the last error ....localhost  0.0.0.0:3000 don't working

PLEASE HEELP :(

**Comment by DuudeXX8** [comment]
sorry for report guys i fix it :)
