### ISSUE TITLE
how can I use Adminator-admin-dashboard with codeigniter3

### ISSUE THREAD

**Issue by a4ankii** [puikinsh/Adminator-admin-dashboard#80]
I just downloaded and setup Adminator-admin-dashboard but I want to merge it with codeigniter 3.is that possible?

**Comment by krzysiekpiasecki** [comment]
It's possible. 

Here you have the examples of incorporating this template into a two well-known PHP frameworks:
https://github.com/kossa/laradminator
https://github.com/krzysiekpiasecki/Symfonator

Please close this ticket, if you don't have any further questions.
