### ISSUE TITLE
Pure Css and Javascript Version

### ISSUE THREAD

**Issue by tenkyu** [puikinsh/Adminator-admin-dashboard#81]
Hi;
I downloaded source file but there ise no pure css files, i tried with npm but did not work. Is there a pure version like "dist" folder.

I need this.

**Comment by AndreiCN** [comment]
We will provide a built version for it in a few days.

**Comment by pmtuan1295** [comment]
waiting for your comment

**Comment by tenkyu** [comment]
There is no dist version, i think the process should be closed when this version exits.

**Comment by pmtuan1295** [comment]
https://drive.google.com/open?id=1Hsgr2yMH4FSR1wjgOVXb-tYno6rNOGqg try it :) i just upload to my google driver

**Comment by tenkyu** [comment]
thank you very much? Do you know how can i disable loading effect when any page while opening.

**Comment by pmtuan1295** [comment]
delete it
`<script>window.addEventListener('load', () => {
        const loader = document.getElementById('loader');
        setTimeout(() => {
          loader.classList.add('fadeOut');
        }, 300);
      });</script>`

**Comment by tenkyu** [comment]
It doen't work but when i removed the `<div id="loader"><div class="spinner"></div></div>` part site is opened.

But this is not distributed version, because all css and js bundled in bundle.js and it loads at bottom of page, this caused page loaded fast but design is not loaded perfectly.

Normally we use css in `<head>` tag that way design working properly on load. but bundle.js at bottom.

How can we use without webpack, pure css files in head and javascsript files at bottom of files and they are seperated. Not bundled.

**Comment by pmtuan1295** [comment]
can you add me on fb?, a have an issue, i can't reslove with this theme :( https://www.facebook.com/Pmtuan1295

**Comment by damms005** [comment]
Hey guys, I find this useful since the Adminator team refused to give plain simple version of their theme: https://github.com/nhatkha1407/ElaAdmin

I hope this helps someone.

**Comment by clain4u** [comment]
[https://github.com/puikinsh/Adminator-admin-dashboard/issues/81#issuecomment-383071426](url) and the "few days" can mean a Year or two.

I still do not understand why the creators are not ready to give a complete pure HTML, CSS and Javascript files independent version. 

So the mention "Easy to use" in the theme description is obsolete, the comments says it all.
