### ISSUE TITLE
ASP.NET Chat

### ISSUE THREAD

**Issue by roro409** [puikinsh/Adminator-admin-dashboard#83]
<h1>Documentation issue</h1>

I'm going to be trying to integrate this template into ASP.NET C# and was a little confused on how I might go about implementing the chat function as the example files simply have the chat hard-coded into the page.  I did not find any documentation.  Can someone point me in the right direction?  Thank you.  
# Current behavior

# Expected behavior 

# Environment
Platform:  Visual Studio
Browser: 

For building issues:
Node:           
NPM:

**Comment by krzysiekpiasecki** [comment]
@roror409 It's only a mock screen. There is no functionality. You must go on your own with a chat server and client. [How to implement chat application in asp.net using c#](http://csharp.net-informations.com/communications/csharp-chat-server-programming.htm)

If you haven't got any further questions, please close this ticket. Thanks.
