### ISSUE TITLE
Error when including adminator's javascript in Angular5 app

### ISSUE THREAD

**Issue by lukasmatta** [puikinsh/Adminator-admin-dashboard#85]
Hello,

when I'm trying to include built javascript (bundle.js and vendor.js) into my Angular5 app, there's this error in the console: `Uncaught TypeError: Cannot read property 'call' of undefined`

Any ideas, how to add Adminator to an existing Angular5 app?

**Comment by krzysiekpiasecki** [comment]
@lukasmatta Angular is based on webpack. Include all js files and let the Angular compile all the files. After resolving this issue, don't forget close this ticket.

**Comment by lukasmatta** [comment]
What do you mean by _all js files_? Should I built Javascript using adminator's webpack config and then include it or include source js files?

**Comment by krzysiekpiasecki** [comment]
Add adminator dependencies to package.json and install them and add static libraries to angular project and import them. Configure Angular. Just read Angular documentation.
