### ISSUE TITLE
Run build/dev error

### ISSUE THREAD

**Issue by jhunax** [puikinsh/Adminator-admin-dashboard#86]
<h1>Bug report</h1>
Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.

# Current behavior
'npm run dev' would throw this error:

Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.

# Expected behavior 

# Environment
Platform: Linux 4.15.0-1007-aws #7-Ubuntu SMP
Browser: N/A

For building issues:
Node:   
v9.11.1        
NPM:    
6.0.0

**Comment by krzysiekpiasecki** [comment]
@jhunax  Look at https://github.com/nuxt/nuxt.js/issues/3042.

**Comment by krzysiekpiasecki** [comment]
@jhunax Did you found the solution?

**Comment by jhunax** [comment]
@krzysiekpiasecki thanks for your feedback.

I reverted my install of nodejs to its original source.

uninstalled/remove nodejs and all other related packages.

re-installed nodejs and this time, I skipped the update.

the webapp now works with some minor warnings but is now working.
