### ISSUE TITLE
Is Node.js required to begin with it??

### ISSUE THREAD

**Issue by kunalvirk** [puikinsh/Adminator-admin-dashboard#9]
Hi Team,

Just wanted to ask that how can i run it locally, as i don't know node.js (i might sound dumb to you), please help me here, i really like the ui, wanted to try it out.

Thanks

**Comment by puikinsh** [comment]
It is required but it will be downloaded as long as you follow setup instructions, so no need to install anything separately. And of course, it can be installed locally.
