### ISSUE TITLE
Sidebar icons not loading

### ISSUE THREAD

**Issue by girishshilkar** [puikinsh/Adminator-admin-dashboard#90]
I have separated different sections like header, sidebar and footer in php files and I am loading the files independently.. Theme is working fine but the sidebar icons are not loading. I have included the vendor.js and bundle.js also. But in the console it is showing the errors for which i have attached the screenshot
![theme errors](https://user-images.githubusercontent.com/13045689/40480370-e18342e4-5f6b-11e8-9929-e0ad4d04311d.PNG)

**Comment by girishshilkar** [comment]
I got the build folder using "npm run build" command. Tell me if i should run some other command. Please help

**Comment by Prabu1785** [comment]
I am also having the same issue.. How to fix this path issue ?
![image](https://user-images.githubusercontent.com/43696210/46270017-93af3480-c562-11e8-9653-6dd0b714a596.png)

**Comment by krzysiekpiasecki** [comment]
Closed due to inactivity. It's not a bug but the implementation problem.  Template successfully incorporated into Symfony - PHP framework here https://github.com/krzysiekpiasecki/Symfonator
