### ISSUE TITLE
How can I merge this template into laravel?

### ISSUE THREAD

**Issue by BourneSuper** [puikinsh/Adminator-admin-dashboard#92]
I am not familiar with frontend tech. How can I merge this template into laravel.
I used 'npm run dev', it work well. But it ran alone.
How to run it with other web server and backend

**Comment by krzysiekpiasecki** [comment]
@BourneSuper See implementation repository - link here #60.  If you have no more question, please close this ticket. Thanks.

**Comment by BourneSuper** [comment]
@krzysiekpiasecki Thanks,that's helpful and time-saving.

**Comment by DinhNC** [comment]
If I want to user Express for backend. How to merge this template into Express?
Thank you,
