### ISSUE TITLE
Customization of Adminator-admin-dashboard. Not able to add more html templates in source folder.

### ISSUE THREAD

**Issue by VikasGemini** [puikinsh/Adminator-admin-dashboard#95]
<h1>Bug report</h1>
<h1>Feature request</h1>
<h1>Support request</h1>
<h1>Documentation issue</h1>

# Current behavior

# Expected behavior 

# Environment
Platform: 
Browser: 

For building issues:
Node:           
NPM:

**Comment by krzysiekpiasecki** [comment]
@VikasGemini  You should provide more information about your problem. You've got event a template issue. BTW you should add html page and register it at ```webpack/plugins/htmlPlugin.js```. Then rebuild the project. 

Close this ticket, if you have no more questions.

**Comment by VikasGemini** [comment]
@krzysiekpiasecki  Thank you for your kind response. You are right about registering it in htmlplugin.js. But we also need to create folder in scripts with same name of template, and also an index.js file in the same folder to make that run otherwise it will not pick the original template.
