### ISSUE TITLE
Accordion effect causes 'TypeError 's' is undefined' in vendor.js file

### ISSUE THREAD

**Issue by ghost** [puikinsh/Adminator-admin-dashboard#97]
<h1>Bug report</h1>

I'm trying to add accordion effect to display additional information for each row in a Datatable. I'm trying to implement this exact code in Adminator: http://jsfiddle.net/QLfMU/116/ 

# Current behavior

When I add the accordion effect to the data table, the table loses is pagination properties, search property, some css etc. The console displays TypeError 's' is undefined in vendor.js file, line 31538. 

# Expected behavior 

Datatable works properly on adding accordion. 

# Environment
Platform: Windows 10
Browser: Chrome/Firefox

For building issues:
Running PHP on XAMPP

**Comment by sublimedatasys** [comment]
Answer=>Hi @nmb0 ,

To get the functionality provided by datatable, you need to  define datatable function with reference to id attribute as below

 “ $('#myTable').DataTable();”

The search and pagination properties will appear and for Accordion effect, Please refer the following URL for detailed documentation:

https://datatables.net/examples/api/row_details.html.

Thank you!
